// Artist seed list — the human-edited source for the whole song catalog.
//
// This file replaced a hand-written list of ~700 [title, artist] pairs. The
// reason is throughput: resolving a hand-written title costs one throttled
// /search per artist *and* can silently resolve to the wrong song, so every
// entry needed a matcher gate. Seeding by artist instead means one /search
// returns that artist's real catalog, and every track harvested from it is by
// definition a real song with a real preview. No matching, no unresolved rows.
//
//   node tools/build-packs.mjs            # build every genre
//   node tools/build-packs.mjs pop rap    # just these
//   node tools/build-packs.mjs --repack   # re-derive from cache, no network
//
// The second number on each row is a fame tier, and it is the only subjective
// judgement in the file:
//
//   1  household name — someone who does not follow the genre knows the hits
//   2  well known inside the genre
//   3  deeper cut
//
// Tier feeds difficulty. It is combined with each track's rank inside its
// artist's own catalog (iTunes returns an artist's songs roughly by
// popularity), and the pack is then split into equal easy/medium/hard bands.
// So tier does not need to be precise — it needs to be roughly ordered. Being
// one tier out moves a song a few places in a ranking, not into the wrong band.

export const GENRES = [
  {
    id: 'pop',
    perArtist: 16,
    color: '#F0C231',
    name: 'Pop',
    code: 'POP',
    blurb: 'Chart pop, late 90s to now',
    // The catalog is tuned for someone born around 2004: the 80s and 90s
    // legacy acts are gone (with a year floor they only ever contributed their
    // late-career filler — Michael Jackson's "Chicago (2014)" was in easy),
    // and the floor sits at the late 90s so the TRL era survives.
    minYear: 1997,
    artists: [
      ['Taylor Swift', 1],
      ['The Weeknd', 1],
      ['Ariana Grande', 1],
      ['Billie Eilish', 1],
      ['Olivia Rodrigo', 1],
      ['Sabrina Carpenter', 1],
      ['Dua Lipa', 1],
      ['Harry Styles', 1],
      ['Ed Sheeran', 1],
      ['Justin Bieber', 1],
      ['Bruno Mars', 1],
      ['Lady Gaga', 1],
      ['Rihanna', 1],
      ['Katy Perry', 1],
      ['Adele', 1],
      ['Beyoncé', 1],
      ['SZA', 1],
      ['Miley Cyrus', 1],
      ['Selena Gomez', 1],
      ['Shawn Mendes', 1],
      ['Chappell Roan', 1],
      ['Tate McRae', 1],
      ['Gracie Abrams', 1],
      ['Benson Boone', 1],
      ['Coldplay', 1],
      ['Maroon 5', 1],
      ['One Direction', 1],
      ['Imagine Dragons', 1],
      ['Justin Timberlake', 1],
      ['Britney Spears', 1],
      ['Christina Aguilera', 1],
      ['Backstreet Boys', 1],
      ['NSYNC', 1],
      ['Usher', 1],
      ['Ne-Yo', 1],
      ['Chris Brown', 1],
      ['Black Eyed Peas', 1],
      ['Halsey', 1],
      ['Camila Cabello', 1],
      ['Charlie Puth', 1],
      ['Sia', 1],
      ['Kelly Clarkson', 1],
      ['P!nk', 1],
      ['Lorde', 1],
      ['Lana Del Rey', 1],
      ['Khalid', 1],
      ['Lewis Capaldi', 1],
      ['Sam Smith', 1],
      ['Teddy Swims', 1],
      ['Noah Kahan', 1],
      ['Alex Warren', 1],
      ['The Chainsmokers', 1],
      ['Calvin Harris', 1],
      ['Avicii', 1],
      ['Marshmello', 1],

      ['Conan Gray', 2],
      ['Troye Sivan', 2],
      ['Charli xcx', 2],
      ['Lola Young', 2],
      ['Gigi Perez', 2],
      ['Tyla', 2],
      ['PinkPantheress', 2],
      ['Addison Rae', 2],
      ['Reneé Rapp', 2],
      ['Myles Smith', 2],
      ['Lauv', 2],
      ['Alec Benjamin', 2],
      ['Bazzi', 2],
      ['ZAYN', 2],
      ['Niall Horan', 2],
      ['Alessia Cara', 2],
      ['Dean Lewis', 2],
      ['James Arthur', 2],
      ['Ruel', 2],
      ['Demi Lovato', 2],
      ['Jonas Brothers', 2],
      ['Avril Lavigne', 2],
      ['Kesha', 2],
      ['Meghan Trainor', 2],
      ['Ellie Goulding', 2],
      ['Ava Max', 2],
      ['Bebe Rexha', 2],
      ['Anne-Marie', 2],
      ['Zara Larsson', 2],
      ['Rita Ora', 2],
      ['Tove Lo', 2],
      ['MARINA', 2],
      ['Carly Rae Jepsen', 2],
      ['Fifth Harmony', 2],
      ['Little Mix', 2],
      ['5 Seconds of Summer', 2],
      ['OneRepublic', 2],
      ['David Guetta', 2],
      ['Kygo', 2],
      ['Zedd', 2],
      ['Martin Garrix', 2],
      ['Alan Walker', 2],
      ['Clean Bandit', 2],
      ['Jonas Blue', 2],
      ['DJ Snake', 2],
      ['Major Lazer', 2],
      ['Jason Derulo', 2],
      ['Flo Rida', 2],
      ['Pitbull', 2],
      ['Nelly Furtado', 2],
      ['Gwen Stefani', 2],
      ['Fergie', 2],
      ['Jennifer Lopez', 2],
      ['Gotye', 2],
      ['Lukas Graham', 2],
      ['Train', 2],
      ['Spice Girls', 2],

      ['Rina Sawayama', 3],
      ['Caroline Polachek', 3],
      ['Kim Petras', 3],
      ['Sigrid', 3],
      ['MØ', 3],
      ['AURORA', 3],
      ['FINNEAS', 3],
      ['Maisie Peters', 3],
      ['Ashnikko', 3],
      ['Olivia Dean', 3],
      ['RAYE', 3],
      ['Mabel', 3],
      ['Sigala', 3],
      ['Galantis', 3],
      ['Robyn', 3],
      ['Jessie J', 3],
      ['Natasha Bedingfield', 3],
      ['No Doubt', 3],
    ],
  },

  {
    id: 'rap',
    perArtist: 16,
    color: '#2E5BE8',
    name: 'Rap',
    code: 'RAP',
    blurb: 'Hip-hop, from the SoundCloud era back to the icons',
    // Tuned for someone born around 2004: the underground boom-bap tail is
    // gone and the SoundCloud, trap and rage generations are in. The icons
    // everyone knows regardless of age stay; the rank cut sorts their hits
    // from their album cuts.
    artists: [
      ['Drake', 1],
      ['Kendrick Lamar', 1],
      ['Travis Scott', 1],
      ['Kanye West', 1],
      ['Eminem', 1],
      ['J. Cole', 1],
      ['Future', 1],
      ['Playboi Carti', 1],
      ['Lil Uzi Vert', 1],
      ['21 Savage', 1],
      ['Metro Boomin', 1],
      ['Lil Baby', 1],
      ['Juice WRLD', 1],
      ['XXXTENTACION', 1],
      ['Post Malone', 1],
      ['Tyler, The Creator', 1],
      ['A$AP Rocky', 1],
      ['Doja Cat', 1],
      ['Nicki Minaj', 1],
      ['Cardi B', 1],
      ['Megan Thee Stallion', 1],
      ['Ice Spice', 1],
      ['Lil Nas X', 1],
      ['Jack Harlow', 1],
      ['Migos', 1],
      ['Lil Wayne', 1],
      ['Snoop Dogg', 1],
      ['Dr. Dre', 1],
      ['2Pac', 1],
      ['The Notorious B.I.G.', 1],
      ['JAY-Z', 1],
      ['Nas', 1],
      ['50 Cent', 1],
      ['Kid Cudi', 1],
      ['Childish Gambino', 1],
      ['Mac Miller', 1],
      ['Yeat', 1],
      ['Ken Carson', 1],
      ['Don Toliver', 1],
      ['Lil Tecca', 1],
      ['Rod Wave', 1],
      ['YoungBoy Never Broke Again', 1],
      ['Trippie Redd', 1],
      ['Lil Peep', 1],
      ['Ski Mask the Slump God', 1],
      ['$uicideboy$', 1],
      ['Lil Durk', 1],
      ['Polo G', 1],
      ['Roddy Ricch', 1],
      ['DaBaby', 1],
      ['Gunna', 1],
      ['Young Thug', 1],
      ['Pop Smoke', 1],
      ['The Kid LAROI', 1],
      ['OutKast', 1],
      ['Missy Elliott', 1],
      ['Ludacris', 1],
      ['Nelly', 1],
      ['Wu-Tang Clan', 1],

      ['BROCKHAMPTON', 2],
      ['Aminé', 2],
      ['Rich Brian', 2],
      ['Joey Bada$$', 2],
      ['Baby Keem', 2],
      ['JID', 2],
      ['Denzel Curry', 2],
      ['Isaiah Rashad', 2],
      ['ScHoolboy Q', 2],
      ['Doechii', 2],
      ['Cordae', 2],
      ['Smino', 2],
      ['Saba', 2],
      ['EARTHGANG', 2],
      ['Vince Staples', 2],
      ['Chance the Rapper', 2],
      ['NLE Choppa', 2],
      ['Lil Yachty', 2],
      ['Lil Tjay', 2],
      ['A Boogie wit da Hoodie', 2],
      ['King Von', 2],
      ['Fivio Foreign', 2],
      ['Sheck Wes', 2],
      ['Kodak Black', 2],
      ['Offset', 2],
      ['Quavo', 2],
      ['Rae Sremmurd', 2],
      ['Destroy Lonely', 2],
      ['Lucki', 2],
      ['$NOT', 2],
      ['JPEGMAFIA', 2],
      ['Iann Dior', 2],
      ['24kGoldn', 2],
      ['Lil Skies', 2],
      ['Lil Mosey', 2],
      ['Lil Pump', 2],
      ['NAV', 2],
      ['GloRilla', 2],
      ['Latto', 2],
      ['Sexyy Red', 2],
      ['Saweetie', 2],
      ['Flo Milli', 2],
      ['Coi Leray', 2],
      ['Wiz Khalifa', 2],
      ['Big Sean', 2],
      ['Meek Mill', 2],
      ['Rick Ross', 2],
      ['2 Chainz', 2],
      ['Gucci Mane', 2],
      ['T.I.', 2],
      ['Busta Rhymes', 2],
      ['Ice Cube', 2],
      ['DMX', 2],
      ['Ja Rule', 2],
      ['Central Cee', 2],
      ['Dave', 2],
      ['Stormzy', 2],
      ['Skepta', 2],
      ['AJ Tracey', 2],
      ['Little Simz', 2],
      ['Machine Gun Kelly', 2],
      ['Logic', 2],
      ['NF', 2],
      ['Russ', 2],

      ['MF DOOM', 3],
      ['Earl Sweatshirt', 3],
      ['Freddie Gibbs', 3],
      ['Danny Brown', 3],
      ['Westside Gunn', 3],
      ['Benny the Butcher', 3],
      ['Run-DMC', 3],
      ['Beastie Boys', 3],
      ['A Tribe Called Quest', 3],
      ['Bone Thugs-N-Harmony', 3],
      ['Three 6 Mafia', 3],
      ['Cypress Hill', 3],
      ['Coolio', 3],
      ['Common', 3],
      ['The Roots', 3],
      ['Method Man', 3],
    ],
  },

  {
    id: 'rock',
    perArtist: 16,
    color: '#E4483F',
    name: 'Rock',
    code: 'RCK',
    blurb: 'Riffs, arenas and college radio',
    artists: [
      ['The Beatles', 1],
      ['Queen', 1],
      ['Led Zeppelin', 1],
      ['Pink Floyd', 1],
      ['The Rolling Stones', 1],
      ['AC/DC', 1],
      ['Nirvana', 1],
      ["Guns N' Roses", 1],
      ['Metallica', 1],
      ['U2', 1],
      ['The Who', 1],
      ['Aerosmith', 1],
      ['Bon Jovi', 1],
      ['Eagles', 1],
      ['Fleetwood Mac', 1],
      ['David Bowie', 1],
      ['Bruce Springsteen', 1],
      ['Red Hot Chili Peppers', 1],
      ['Green Day', 1],
      ['Foo Fighters', 1],
      ['Pearl Jam', 1],
      ['Radiohead', 1],
      ['Oasis', 1],
      ['Blur', 1],
      ['The Killers', 1],
      ['Arctic Monkeys', 1],
      ['Muse', 1],
      ['Linkin Park', 1],
      ['Nickelback', 1],
      ['blink-182', 1],
      ['Weezer', 1],
      ['The Smashing Pumpkins', 1],
      ['Soundgarden', 1],
      ['Alice In Chains', 1],
      ['Stone Temple Pilots', 1],
      ['R.E.M.', 1],
      ['The Cure', 1],
      ['The Police', 1],
      ['Dire Straits', 1],
      ['Journey', 1],
      ['Boston', 1],
      ['Van Halen', 1],
      ['Def Leppard', 1],
      ['Deep Purple', 1],
      ['Black Sabbath', 1],
      ['Lynyrd Skynyrd', 1],
      ['Heart', 1],
      ['The Doors', 1],
      ['Creedence Clearwater Revival', 1],
      ['Jimi Hendrix', 1],

      // The 2000s-and-on half of the crate. Anything indie- or bedroom-leaning
      // lives in the Indie crate instead; one song belongs to one pack.
      ['My Chemical Romance', 1],
      ['Paramore', 1],
      ['Fall Out Boy', 1],
      ['Panic! At The Disco', 1],
      ['Twenty One Pilots', 1],
      ['Deftones', 1],
      ['System of a Down', 1],
      ['Slipknot', 1],
      ['Bring Me the Horizon', 1],
      ['The Strokes', 1],
      ['Cage The Elephant', 1],
      ['Gorillaz', 1],
      ['Sum 41', 1],
      ['The Offspring', 1],
      ['Evanescence', 1],

      ['The White Stripes', 2],
      ['Kings of Leon', 2],
      ['The Black Keys', 2],
      ['Franz Ferdinand', 2],
      ['Bloc Party', 2],
      ['Interpol', 2],
      ['Yeah Yeah Yeahs', 2],
      ['Queens of the Stone Age', 2],
      ['Arcade Fire', 2],
      ['Kasabian', 2],
      ['Wolf Alice', 2],
      ['Royal Blood', 2],
      ['Catfish and the Bottlemen', 2],
      ['Sam Fender', 2],
      ['Fontaines D.C.', 2],
      ['IDLES', 2],
      ['Wet Leg', 2],
      ['Inhaler', 2],
      ['The Last Dinner Party', 2],
      ['Måneskin', 2],
      ['Sleep Token', 2],
      ['Bad Omens', 2],
      ['Ghost', 2],
      ['Avenged Sevenfold', 2],
      ['Korn', 2],
      ['Papa Roach', 2],
      ['Breaking Benjamin', 2],
      ['Three Days Grace', 2],
      ['Turnstile', 2],
      ['Pierce The Veil', 2],
      ['Sleeping With Sirens', 2],
      ['All Time Low', 2],
      ['Good Charlotte', 2],
      ['Simple Plan', 2],
      ['Jimmy Eat World', 2],
      ['Taking Back Sunday', 2],
      ['Brand New', 2],
      ['Rage Against the Machine', 2],
      ['TOOL', 2],
      ['Nine Inch Nails', 2],
      ['Incubus', 2],
      ['Sublime', 2],
      ['Third Eye Blind', 2],
      ['Goo Goo Dolls', 2],
      ['Pixies', 2],
      ['The Smiths', 2],
      ['Joy Division', 2],
      ['New Order', 2],
      ['Depeche Mode', 2],
      ['Talking Heads', 2],
      ['The Clash', 2],
      ['Ramones', 2],
      ['Ozzy Osbourne', 2],
      ['KISS', 2],
      ['Iron Maiden', 2],
      ['Rush', 2],
      ['Toto', 2],
      ['Tom Petty and the Heartbreakers', 2],

      ['Highly Suspect', 3],
      ['Nothing But Thieves', 3],
      ['Modest Mouse', 3],
      ['Death Cab for Cutie', 3],
      ['The Shins', 3],
      ['The National', 3],
      ['Sonic Youth', 3],
      ['Pavement', 3],
      ['Dinosaur Jr.', 3],
      ['My Bloody Valentine', 3],
      ['At the Drive-In', 3],
      ['The Mars Volta', 3],
    ],
  },

  {
    id: 'indie',
    perArtist: 16,
    color: '#8FD3F4',
    name: 'Indie',
    code: 'IND',
    blurb: 'Bedroom pop, indie rock and the alt-R&B in between',
    // The crate a 2004-born actually lives in: keshi, Laufey, grentperez,
    // Joji, beabadoobee, Clairo, and the indie-rock lineage they came out of.
    // Acts that used to sit in Rock's shoegaze/dream-pop tail moved here.
    artists: [
      ['keshi', 1],
      ['Laufey', 1],
      ['grentperez', 1],
      ['Joji', 1],
      ['beabadoobee', 1],
      ['Clairo', 1],
      ['Wallows', 1],
      ['Dominic Fike', 1],
      ['Rex Orange County', 1],
      ['Cavetown', 1],
      ['girl in red', 1],
      ['mxmtoon', 1],
      ['Lizzy McAlpine', 1],
      ['Phoebe Bridgers', 1],
      ['boygenius', 1],
      ['Mitski', 1],
      ['Men I Trust', 1],
      ['Still Woozy', 1],
      ['Dayglow', 1],
      ['Peach Pit', 1],
      ['The Marías', 1],
      ['Cigarettes After Sex', 1],
      ['Beach House', 1],
      ['Mac DeMarco', 1],
      ['Tame Impala', 1],
      ['MGMT', 1],
      ['The 1975', 1],
      ['The Neighbourhood', 1],
      ['wave to earth', 1],
      ['Steve Lacy', 1],
      ['Daniel Caesar', 1],
      ['Frank Ocean', 1],
      ['Brent Faiyaz', 1],
      ['Giveon', 1],
      ['d4vd', 1],
      ['TV Girl', 1],
      ['Djo', 1],
      ['Hozier', 1],
      ['Zach Bryan', 1],
      ['Vampire Weekend', 1],
      ['Glass Animals', 1],
      ['Foster The People', 1],
      ['Two Door Cinema Club', 1],
      ['Sombr', 1],
      ['Malcolm Todd', 1],
      ['Role Model', 1],

      ['Bruno Major', 2],
      ['Omar Apollo', 2],
      ['Kali Uchis', 2],
      ['NIKI', 2],
      ['Jeremy Zucker', 2],
      ['Chelsea Cutler', 2],
      ['LANY', 2],
      ['Bon Iver', 2],
      ['Sufjan Stevens', 2],
      ['Alex G', 2],
      ['Car Seat Headrest', 2],
      ['Japanese Breakfast', 2],
      ['Soccer Mommy', 2],
      ['Snail Mail', 2],
      ['Faye Webster', 2],
      ['Big Thief', 2],
      ['Adrianne Lenker', 2],
      ['Fleet Foxes', 2],
      ['Elliott Smith', 2],
      ['alt-J', 2],
      ['Vance Joy', 2],
      ['Passion Pit', 2],
      ['COIN', 2],
      ['half·alive', 2],
      ['Hippo Campus', 2],
      ['boy pablo', 2],
      ['Cuco', 2],
      ['Current Joys', 2],
      ['Surf Curse', 2],
      ['The Backseat Lovers', 2],
      ['Briston Maroney', 2],
      ['Ethel Cain', 2],
      ['Weyes Blood', 2],
      ['Arlo Parks', 2],
      ['Slowdive', 2],
      ['Mazzy Star', 2],
      ['Cocteau Twins', 2],
      ['Duster', 2],
      ['Alvvays', 2],
      ['Mk.gee', 2],
      ['Dijon', 2],
      ['Blood Orange', 2],
      ['Toro y Moi', 2],
      ['Washed Out', 2],
      ['Portugal. The Man', 2],
      ['Young the Giant', 2],
      ['WALK THE MOON', 2],
      ['The Lumineers', 2],
      ['Mumford & Sons', 2],
      ['Of Monsters and Men', 2],
      ['Florence + The Machine', 2],
      ['Lord Huron', 2],
      ['Declan McKenna', 2],
      ['Bakar', 2],
      ['HONNE', 2],
      ['Ritt Momney', 2],
      ['Yot Club', 2],
      ['Sunset Rollercoaster', 2],

      ['Iron & Wine', 3],
      ['The Paper Kites', 3],
      ['Novo Amor', 3],
      ['Gregory Alan Isakov', 3],
      ['Cults', 3],
      ['Grouplove', 3],
      ['Phoenix', 3],
      ['Empire of the Sun', 3],
      ['Yo La Tengo', 3],
      ['Built to Spill', 3],
      ['Wednesday', 3],
      ['MJ Lenderman', 3],
      ['Black Country, New Road', 3],
      ['black midi', 3],
    ],
  },

  {
    id: 'anime',
    perArtist: 60,
    color: '#E8672A',
    name: 'Anime',
    code: 'ANI',
    blurb: 'Openings, endings and inserts',
    // Only tracks that match the AnimeThemes.moe catalog are kept, and each one
    // carries its source ("Kimetsu no Yaiba OP1"). The cap is high because the
    // theme match is the real filter: an anisong specialist's catalog is dense
    // with themes, and everything else falls out.
    themeMatch: true,
    nativeScript: true,
    // Fetch by resolved artistId, not by name search: one-word acts like LiSA,
    // Eve and FLOW drown in same-name noise otherwise. See searchArtistById.
    lookupArtist: true,
    artists: [
      ['LiSA', 1], ['Aimer', 1], ['Kenshi Yonezu', 1], ['YOASOBI', 1],
      ['Ado', 1], ['Eve', 1], ['RADWIMPS', 1], ['King Gnu', 1],
      ['Official HIGE DANdism', 1], ['Mrs. GREEN APPLE', 1], ['Vaundy', 1],
      ['ONE OK ROCK', 1], ['UVERworld', 1], ['FLOW', 1],
      ['ASIAN KUNG-FU GENERATION', 1], ['Ikimonogakari', 1],
      ['Porno Graffitti', 1], ['BUMP OF CHICKEN', 1], ['Creepy Nuts', 1],
      ['milet', 1], ['Gen Hoshino', 1], ['back number', 1], ['Fujii Kaze', 1],
      ['Tatsuya Kitani', 1], ['SiM', 1], ['Linked Horizon', 1],
      ['MAN WITH A MISSION', 1], ['SPYAIR', 1], ['EGOIST', 1],
      ['Yoko Takahashi', 1], ['Hiroyuki Sawano', 1], ['SawanoHiroyuki[nZk]', 1],

      ['KANA-BOON', 2], ['BURNOUT SYNDROMES', 2], ['sumika', 2],
      ['Vickeblanka', 2], ['ClariS', 2], ['fripSide', 2], ['Eir Aoi', 2],
      ['ReoNa', 2], ['ASCA', 2], ['Konomi Suzuki', 2], ['Luna Haruna', 2],
      ['Nana Mizuki', 2], ["May'n", 2], ['angela', 2], ['GRANRODEO', 2],
      ['JAM Project', 2], ['T.M.Revolution', 2], ['Masaaki Endoh', 2],
      ['Ichirou Mizuki', 2], ['Megumi Hayashibara', 2], ['Maaya Sakamoto', 2],
      ['Kalafina', 2], ['supercell', 2], ['Aqours', 2], ["μ's", 2],
      ['Roselia', 2], ["Poppin'Party", 2], ['ZUTOMAYO', 2], ['Reol', 2],
      ['MAXIMUM THE HORMONE', 2], ["L'Arc~en~Ciel", 2], ['Do As Infinity', 2],
      ['abingdon boys school', 2], ['HOME MADE Kazoku', 2], ['ORANGE RANGE', 2],
      ['BEAT CRUSADERS', 2], ['NICO Touches the Walls', 2], ['Sambomaster', 2],
      ['Aqua Timez', 2], ['YUI', 2], ['miwa', 2], ['SCANDAL', 2],
      ['Stereopony', 2], ['Galileo Galilei', 2], ['Goose house', 2],
      ['Uru', 2], ['Sukima Switch', 2], ['Little Glee Monster', 2],
      ['UNISON SQUARE GARDEN', 2], ['BLUE ENCOUNT', 2],
      ['THE ORAL CIGARETTES', 2], ['04 Limited Sazabys', 2],
      ['Fear, and Loathing in Las Vegas', 2], ['coldrain', 2],
      ['Ling tosite sigure', 2], ['TK from Ling tosite sigure', 2],
      ['amazarashi', 2], ['[Alexandros]', 2], ['Novelbright', 2],
      ['PEOPLE 1', 2], ['ano', 2], ['Cö shu Nie', 2], ['Who-ya Extended', 2],
      ['MYTH & ROID', 2], ['Yorushika', 2],

      ['OxT', 3], ['Masayoshi Oishi', 3], ['ZAQ', 3], ['GARNiDELiA', 3],
      ['Mili', 3], ['Kishida Kyoudan & The Akeboshi Rockets', 3],
      ['ChouCho', 3], ['Lia', 3], ['See-Saw', 3], ['FictionJunction', 3],
      ['TrySail', 3], ['Sphere', 3], ['Ai Higuchi', 3], ['sajou no hana', 3],
      ['Wagakki Band', 3], ['yama', 3], ['Tani Yuuki', 3], ['Omoinotake', 3],
      ['Hitsujibungaku', 3], ['Kessoku Band', 3], ['Aina The End', 3],
      ['Anonymouz', 3], ['Sangatsu no Phantasia', 3], ['halca', 3],
      ['Minami', 3], ['Mafumafu', 3], ['Kankaku Piero', 3],
      ['Survive Said The Prophet', 3], ['DISH//', 3], ['Saucy Dog', 3],
      ['Chico with HoneyWorks', 3], ['HoneyWorks', 3], ['TRUE', 3],
      ['yanaginagi', 3], ['Minori Chihara', 3], ['Yui Horie', 3],
      ['KOTOKO', 3], ['Rie fu', 3], ['High and Mighty Color', 3],
      ['FLOW-BACK', 3],

      ['Sayuri', 3], ['Nanawo Akari', 3], ['Aimyon', 2], ['JUDY AND MARY', 2],
      ['Hikaru Utada', 1], ['YUKI', 2], ['the pillows', 2], ['the peggies', 3],
      ['MY FIRST STORY', 2], ['HYDE', 2], ['TUYU', 3], ['Myuk', 3],
      ['fhana', 3], ['nano', 3], ['Yuki Kajiura', 2], ['ALI', 3],
      ['Queen Bee', 2], ['Yoh Kamiyama', 3], ['Keina Suda', 3],
      ['Hitorie', 3], ['Miyuna', 3], ['Luck Life', 3],
      ['Hironobu Kageyama', 2], ['Masatoshi Ono', 3], ['Yuzu', 2],
      ['WANDS', 2], ['Maki Ohguro', 3], ['BAAD', 3], ['FIELD OF VIEW', 3],
      ['ZARD', 2], ["B'z", 2], ['Mai Kuraki', 2], ['GARNET CROW', 3],
      ['TWO-MIX', 3], ['m.o.v.e', 3], ['Mikuni Shimokawa', 3],
      ['Masami Okui', 3], ['Shoko Nakagawa', 3], ['AKINO from bless4', 3],
      ['CHEMISTRY', 3], ['Nami Tamaki', 3], ['Fujifabric', 3], ['SID', 2],
      ['Nightmare', 3], ['Anna Tsuchiya', 3], ['Tommy heavenly6', 3],
      ['DOES', 3],
      ['MINMI', 3], ['Nujabes', 3], ['Takanori Nishikawa', 3],
      ['Yousei Teikoku', 3], ['Machico', 3], ['Riko Azuna', 3],
      ['Chiai Fujikawa', 3], ['MADKID', 3], ['RAISE A SUILEN', 3],
      ['flumpool', 3], ['Ryokuoushoku Shakai', 2], ['Tainaka Sachi', 3],
    ],
  },

  {
    id: 'kpop',
    perArtist: 16,
    color: '#BC5FE3',
    name: 'K-Pop',
    code: 'KOR',
    blurb: 'Idols, soloists and the Hallyu wave',
    nativeScript: true,
    artists: [
      ['BTS', 1],
      ['BLACKPINK', 1],
      ['TWICE', 1],
      ['EXO', 1],
      ['Red Velvet', 1],
      ['SEVENTEEN', 1],
      ['Stray Kids', 1],
      ['NCT 127', 1],
      ['NCT DREAM', 1],
      ['aespa', 1],
      ['ITZY', 1],
      ['IVE', 1],
      ['NewJeans', 1],
      ['LE SSERAFIM', 1],
      ['(G)I-DLE', 1],
      ['TOMORROW X TOGETHER', 1],
      ['ENHYPEN', 1],
      ['ATEEZ', 1],
      ['MONSTA X', 1],
      ['GOT7', 1],
      ['BIGBANG', 1],
      ['2NE1', 1],
      ["Girls' Generation", 1],
      ['SHINee', 1],
      ['SUPER JUNIOR', 1],
      ['Wonder Girls', 1],
      ['IU', 1],
      ['PSY', 1],
      ['G-DRAGON', 1],
      ['TAEYANG', 1],

      ['CL', 2],
      ['SUNMI', 2],
      ['HyunA', 2],
      ['CHUNG HA', 2],
      ['TAEYEON', 2],
      ['JENNIE', 2],
      ['JISOO', 2],
      ['ROSÉ', 2],
      ['LISA', 2],
      ['Jung Kook', 2],
      ['Jimin', 2],
      ['V', 2],
      ['j-hope', 2],
      ['RM', 2],
      ['Agust D', 2],
      ['ZICO', 2],
      ['Jay Park', 2],
      ['DEAN', 2],
      ['Crush', 2],
      ['HEIZE', 2],
      ['Zion.T', 2],
      ['BAEKHYUN', 2],
      ['KAI', 2],
      ['TAEMIN', 2],
      ['MAMAMOO', 2],
      ['GFRIEND', 2],
      ['OH MY GIRL', 2],
      ['WJSN', 2],
      ['EVERGLOW', 2],
      ['Dreamcatcher', 2],
      ['LOONA', 2],
      ['fromis_9', 2],
      ['STAYC', 2],
      ['Kep1er', 2],
      ['NMIXX', 2],
      ['Apink', 2],
      ['T-ARA', 2],
      ['KARA', 2],
      ['Rain', 2],
      ['BoA', 2],
      ['SISTAR', 2],
      ['4MINUTE', 2],
      ['miss A', 2],
      ['f(x)', 2],
      ['After School', 2],
      ['Brown Eyed Girls', 2],
      ['TVXQ!', 2],
      ['HIGHLIGHT', 2],
      ['B1A4', 2],
      ['INFINITE', 2],
      ['VIXX', 2],
      ['BTOB', 2],
      ['Block B', 2],
      ['WINNER', 2],
      ['iKON', 2],

      ['DAY6', 3],
      ['N.Flying', 3],
      ['The Rose', 3],
      ['Xdinary Heroes', 3],
      ['Epik High', 3],
      ['Dynamic Duo', 3],
      ['Beenzino', 3],
      ['pH-1', 3],
      ['LEE HI', 3],
      ['AKMU', 3],
      ['BOL4', 3],
      ['10CM', 3],
      ['Paul Kim', 3],
      ['SAM KIM', 3],
      ['JANNABI', 3],
      ['Standing Egg', 3],
      ['Younha', 3],
      ['Baek Yerin', 3],
      ['Sunwoojunga', 3],
      ['CHEEZE', 3],
      ['Car, the garden', 3],
      ['Nell', 3],
      ['Hyukoh', 3],
      ['SE SO NEON', 3],
      ['Silica Gel', 3],
      ['ADOY', 3],
      ['Lucy', 3],
      ['QWER', 3],
      ['BIBI', 3],
      ['Colde', 3],
      ['offonoff', 3],
      ['GIRIBOY', 3],
      ['Woo', 3],
      ['Sokodomo', 3],
      ['Balming Tiger', 3],
    ],
  },

  {
    id: 'vgm',
    perArtist: 40,
    color: '#4ACF8B',
    name: 'Game Music',
    code: 'VGM',
    blurb: 'Chiptune, boss themes and open worlds',
    // The store credits arrangers, orchestras and sound teams rather than the
    // named composer, so the artist-name gate has to come off.
    nativeScript: true,
    // Each track carries the game it is from (peeled out of the album title
    // by workFromAlbum), so naming the game counts as a correct guess.
    mediaFromAlbum: true,
    artists: [
      ['Koji Kondo', 1], ['Nobuo Uematsu', 1], ['Yasunori Mitsuda', 1], ['Motoi Sakuraba', 1],
      ['Shoji Meguro', 1], ['Yoko Shimomura', 1], ['Keiichi Okabe', 1], ['Toby Fox', 1],
      ['Mick Gordon', 1], ['Austin Wintory', 1], ['Jesper Kyd', 1], ['Jeremy Soule', 1],
      ['Martin O\'Donnell', 1], ['Gareth Coker', 1], ['Darren Korb', 1], ['Lena Raine', 1],
      ['Grant Kirkhope', 2], ['David Wise', 2], ['Yuzo Koshiro', 2], ['Hirokazu Tanaka', 2],
      ['Junichi Masuda', 2], ['Go Ichinose', 2], ['Kenji Ito', 2], ['Hitoshi Sakimoto', 2],
      ['Masashi Hamauzu', 2], ['Naoshi Mizuta', 2], ['Yoko Kanno', 2], ['Akira Yamaoka', 2],
      ['Tomoya Ohtani', 2], ['Jun Senoue', 2], ['Michiru Yamane', 2], ['Kow Otani', 2],
      ['Christopher Larkin', 2], ['Disasterpeace', 2], ['C418', 2], ['Lena Chappelle', 2],
      ['Inon Zur', 3], ['Bear McCreary', 3], ['Sarah Schachner', 3], ['Petri Alanko', 3],
      ['Olivier Deriviere', 3], ['Ben Prunty', 3], ['Laura Shigihara', 3],
      ['Kumi Tanioka', 3], ['Manami Matsumae', 3], ['Takeshi Abo', 3],
      ['Koichi Sugiyama', 2], ['Masayoshi Soken', 2], ['Yuka Kitamura', 2],
      ['Go Shiina', 2], ['Masafumi Takada', 2], ['Norihiko Hibino', 3],
      ['Keiki Kobayashi', 3], ['Kenji Yamamoto', 3], ['Kazumi Totaka', 3],
      ['Hideki Naganuma', 2], ['Ippo Yamada', 3], ['Marcin Przybylowicz', 2],
      ['Piotr Musial', 3], ['Borislav Slavov', 3], ['Jack Wall', 3],
      ['Sam Hulick', 3], ['Cris Velasco', 3], ['Winifred Phillips', 3],
      ['Danny Baranowsky', 2], ['Anamanaguchi', 2], ['Chipzel', 3],
      ['Lifeformed', 3], ['ConcernedApe', 1], ['Scott Lloyd Shelly', 2],
    ],
  },
];

export const GENRE_BY_ID = Object.fromEntries(GENRES.map((g) => [g.id, g]));
