// Artist seed list — the human-edited source for the whole song catalog.
//
// This file replaced a hand-written list of ~700 [title, artist] pairs. The
// reason is throughput: resolving a hand-written title costs one throttled
// /search per artist *and* can silently resolve to the wrong song, so every
// entry needed a matcher gate. Seeding by artist instead means one /search
// returns that artist's real catalog, and every track harvested from it is by
// definition a real song with a real preview. No matching, no unresolved rows.
//
//   node tools/build-packs.mjs            # build every genre
//   node tools/build-packs.mjs pop rap    # just these
//   node tools/build-packs.mjs --repack   # re-derive from cache, no network
//
// The second number on each row is a fame tier, and it is the only subjective
// judgement in the file:
//
//   1  household name — someone who does not follow the genre knows the hits
//   2  well known inside the genre
//   3  deeper cut
//
// Tier feeds difficulty. It is combined with each track's rank inside its
// artist's own catalog (iTunes returns an artist's songs roughly by
// popularity), and the pack is then split into equal easy/medium/hard bands.
// So tier does not need to be precise — it needs to be roughly ordered. Being
// one tier out moves a song a few places in a ranking, not into the wrong band.

export const GENRES = [
  {
    id: 'pop',
    perArtist: 16,
    color: '#F0C231',
    name: 'Pop',
    code: 'POP',
    blurb: 'Chart pop, 2000 to now',
    minYear: 2000,
    artists: [
      ['Michael Jackson', 1],
      ['Madonna', 1],
      ['Whitney Houston', 1],
      ['Mariah Carey', 1],
      ['Prince', 1],
      ['George Michael', 1],
      ['Elton John', 1],
      ['ABBA', 1],
      ['Cyndi Lauper', 1],
      ['a-ha', 1],
      ['Wham!', 1],
      ['Backstreet Boys', 1],
      ['NSYNC', 1],
      ['Spice Girls', 1],
      ['Britney Spears', 1],
      ['Christina Aguilera', 1],
      ['Justin Timberlake', 1],
      ['Katy Perry', 1],
      ['Lady Gaga', 1],
      ['Rihanna', 1],
      ['Taylor Swift', 1],
      ['Adele', 1],
      ['Bruno Mars', 1],
      ['Ed Sheeran', 1],
      ['Justin Bieber', 1],
      ['Ariana Grande', 1],
      ['The Weeknd', 1],
      ['Dua Lipa', 1],
      ['Harry Styles', 1],
      ['Billie Eilish', 1],
      ['Olivia Rodrigo', 1],
      ['Sabrina Carpenter', 1],
      ['Miley Cyrus', 1],
      ['Selena Gomez', 1],
      ['Shawn Mendes', 1],
      ['Maroon 5', 1],
      ['Coldplay', 1],
      ['P!nk', 1],
      ['Kelly Clarkson', 1],
      ['One Direction', 1],
      ['Lionel Richie', 1],
      ['Phil Collins', 1],
      ['Cher', 1],
      ['Tina Turner', 1],

      ['Avril Lavigne', 2],
      ['Kesha', 2],
      ['Demi Lovato', 2],
      ['Jonas Brothers', 2],
      ['Camila Cabello', 2],
      ['Halsey', 2],
      ['Charlie Puth', 2],
      ['Meghan Trainor', 2],
      ['Sia', 2],
      ['Ellie Goulding', 2],
      ['Zara Larsson', 2],
      ['Anne-Marie', 2],
      ['Rita Ora', 2],
      ['Bebe Rexha', 2],
      ['Tove Lo', 2],
      ['MARINA', 2],
      ['Lorde', 2],
      ['Lana Del Rey', 2],
      ['Gwen Stefani', 2],
      ['No Doubt', 2],
      ['Nelly Furtado', 2],
      ['Natasha Bedingfield', 2],
      ['Jason Derulo', 2],
      ['Flo Rida', 2],
      ['Pitbull', 2],
      ['OneRepublic', 2],
      ['Train', 2],
      ['The Chainsmokers', 2],
      ['Clean Bandit', 2],
      ['Calvin Harris', 2],
      ['David Guetta', 2],
      ['Avicii', 2],
      ['Kygo', 2],
      ['Zedd', 2],
      ['Robyn', 2],
      ['Kylie Minogue', 2],
      ['Jessie J', 2],
      ['Carly Rae Jepsen', 2],
      ['Duran Duran', 2],
      ['Tears for Fears', 2],
      ['Eurythmics', 2],
      ['Blondie', 2],
      ['The Bangles', 2],
      ['Roxette', 2],
      ['Ace of Base', 2],
      ['Aqua', 2],
      ['Little Mix', 2],
      ['Fifth Harmony', 2],
      ['5 Seconds of Summer', 2],
      ['Hanson', 2],
      ['Natalie Imbruglia', 2],
      ['Gotye', 2],
      ['Lukas Graham', 2],
      ['Hall & Oates', 2],
      ['Culture Club', 2],
      ['Pet Shop Boys', 2],
      ['The Human League', 2],
      ['Rick Astley', 2],
      ['Bonnie Tyler', 2],
      ['Belinda Carlisle', 2],
      ['INXS', 2],
      ['Simple Minds', 2],
      ['Spandau Ballet', 2],

      ['Chappell Roan', 3],
      ['Tate McRae', 3],
      ['Gracie Abrams', 3],
      ['Reneé Rapp', 3],
      ['Benson Boone', 3],
      ['Teddy Swims', 3],
      ['Noah Kahan', 3],
      ['Conan Gray', 3],
      ['Troye Sivan', 3],
      ['Rina Sawayama', 3],
      ['Caroline Polachek', 3],
      ['Charli xcx', 3],
      ['Kim Petras', 3],
      ['Ava Max', 3],
      ['Sigrid', 3],
      ['MØ', 3],
      ['Betty Who', 3],
      ['Christine and the Queens', 3],
      ['AURORA', 3],
      ['Birdy', 3],
      ['Freya Ridings', 3],
      ['Jessie Ware', 3],
      ['Róisín Murphy', 3],
      ['Erasure', 3],
      ['Soft Cell', 3],
      ['Kim Wilde', 3],
      ['Debbie Gibson', 3],
      ['Samantha Fox', 3],
      ['Sophie Ellis-Bextor', 3],
      ['Sugababes', 3],
      ['Girls Aloud', 3],
      ['All Saints', 3],
      ['S Club 7', 3],
      ['Steps', 3],
      ['Nicola Roberts', 3],
    ],
  },

  {
    id: 'rap',
    perArtist: 16,
    color: '#2E5BE8',
    name: 'Rap',
    code: 'RAP',
    blurb: 'Hip-hop from the block parties on',
    artists: [
      ['Eminem', 1],
      ['Drake', 1],
      ['Kanye West', 1],
      ['JAY-Z', 1],
      ['Kendrick Lamar', 1],
      ['Nicki Minaj', 1],
      ['Travis Scott', 1],
      ['Lil Wayne', 1],
      ['Snoop Dogg', 1],
      ['Dr. Dre', 1],
      ['2Pac', 1],
      ['The Notorious B.I.G.', 1],
      ['Nas', 1],
      ['50 Cent', 1],
      ['Ice Cube', 1],
      ['Missy Elliott', 1],
      ['Cardi B', 1],
      ['Post Malone', 1],
      ['J. Cole', 1],
      ['Future', 1],
      ['Migos', 1],
      ['Tyler, The Creator', 1],
      ['A$AP Rocky', 1],
      ['Childish Gambino', 1],
      ['Wiz Khalifa', 1],
      ['Big Sean', 1],
      ['Meek Mill', 1],
      ['Lil Baby', 1],
      ['Lil Uzi Vert', 1],
      ['21 Savage', 1],
      ['Playboi Carti', 1],
      ['Doja Cat', 1],
      ['Megan Thee Stallion', 1],
      ['Ludacris', 1],
      ['T.I.', 1],
      ['Busta Rhymes', 1],
      ['Kid Cudi', 1],
      ['Jack Harlow', 1],
      ['Juice WRLD', 1],
      ['XXXTENTACION', 1],
      ['Lil Nas X', 1],
      ['OutKast', 1],
      ['Wu-Tang Clan', 1],
      ['Run-DMC', 1],
      ['Beastie Boys', 1],

      ['Public Enemy', 2],
      ['LL COOL J', 2],
      ['Salt-N-Pepa', 2],
      ['MC Hammer', 2],
      ['Coolio', 2],
      ['Warren G', 2],
      ['Bone Thugs-N-Harmony', 2],
      ['Cypress Hill', 2],
      ['Mobb Deep', 2],
      ['Gang Starr', 2],
      ['A Tribe Called Quest', 2],
      ['De La Soul', 2],
      ['Three 6 Mafia', 2],
      ['Juvenile', 2],
      ['DMX', 2],
      ['Ja Rule', 2],
      ['Fabolous', 2],
      ['Method Man', 2],
      ['Redman', 2],
      ['Ghostface Killah', 2],
      ['Raekwon', 2],
      ['GZA', 2],
      ['Common', 2],
      ['Talib Kweli', 2],
      ['Yasiin Bey', 2],
      ['The Roots', 2],
      ['Chance the Rapper', 2],
      ['Vince Staples', 2],
      ['Denzel Curry', 2],
      ['JID', 2],
      ['Isaiah Rashad', 2],
      ['Smino', 2],
      ['Saba', 2],
      ['EARTHGANG', 2],
      ['Rapsody', 2],
      ['Little Simz', 2],
      ['Loyle Carner', 2],
      ['AJ Tracey', 2],
      ['Central Cee', 2],
      ['Dave', 2],
      ['Stormzy', 2],
      ['Skepta', 2],
      ['Roddy Ricch', 2],
      ['Polo G', 2],
      ['DaBaby', 2],
      ['Latto', 2],
      ['GloRilla', 2],
      ['Ice Spice', 2],
      ['Machine Gun Kelly', 2],
      ['Logic', 2],
      ['Rick Ross', 2],
      ['2 Chainz', 2],
      ['Gucci Mane', 2],
      ['Young Thug', 2],
      ['Gunna', 2],
      ['Lil Yachty', 2],
      ['Lil Durk', 2],
      ['NLE Choppa', 2],
      ['Sexyy Red', 2],

      ['MF DOOM', 3],
      ['Aesop Rock', 3],
      ['Danny Brown', 3],
      ['Freddie Gibbs', 3],
      ['Action Bronson', 3],
      ['Roc Marciano', 3],
      ['billy woods', 3],
      ['Mach-Hommy', 3],
      ['Boldy James', 3],
      ['Westside Gunn', 3],
      ['Conway the Machine', 3],
      ['Benny the Butcher', 3],
      ['Curren$y', 3],
      ['Larry June', 3],
      ['Navy Blue', 3],
      ['MIKE', 3],
      ['Earl Sweatshirt', 3],
      ['Pink Siifu', 3],
      ['redveil', 3],
      ['Baby Keem', 3],
      ['Maxo Kream', 3],
      ['Kenny Mason', 3],
      ['Digable Planets', 3],
      ['The Pharcyde', 3],
      ['Souls of Mischief', 3],
      ['Jurassic 5', 3],
      ['Dilated Peoples', 3],
      ['Blackalicious', 3],
      ['Atmosphere', 3],
      ['Brother Ali', 3],
      ['Open Mike Eagle', 3],
      ['Quelle Chris', 3],
      ['Armand Hammer', 3],
      ['Ka', 3],
      ['Your Old Droog', 3],
    ],
  },

  {
    id: 'rock',
    perArtist: 16,
    color: '#E4483F',
    name: 'Rock',
    code: 'RCK',
    blurb: 'Riffs, arenas and college radio',
    artists: [
      ['The Beatles', 1],
      ['Queen', 1],
      ['Led Zeppelin', 1],
      ['Pink Floyd', 1],
      ['The Rolling Stones', 1],
      ['AC/DC', 1],
      ['Nirvana', 1],
      ["Guns N' Roses", 1],
      ['Metallica', 1],
      ['U2', 1],
      ['The Who', 1],
      ['Aerosmith', 1],
      ['Bon Jovi', 1],
      ['Eagles', 1],
      ['Fleetwood Mac', 1],
      ['David Bowie', 1],
      ['Bruce Springsteen', 1],
      ['Red Hot Chili Peppers', 1],
      ['Green Day', 1],
      ['Foo Fighters', 1],
      ['Pearl Jam', 1],
      ['Radiohead', 1],
      ['Oasis', 1],
      ['Blur', 1],
      ['The Killers', 1],
      ['Arctic Monkeys', 1],
      ['Muse', 1],
      ['Linkin Park', 1],
      ['Nickelback', 1],
      ['blink-182', 1],
      ['Weezer', 1],
      ['The Smashing Pumpkins', 1],
      ['Soundgarden', 1],
      ['Alice In Chains', 1],
      ['Stone Temple Pilots', 1],
      ['R.E.M.', 1],
      ['The Cure', 1],
      ['The Police', 1],
      ['Dire Straits', 1],
      ['Journey', 1],
      ['Boston', 1],
      ['Van Halen', 1],
      ['Def Leppard', 1],
      ['Deep Purple', 1],
      ['Black Sabbath', 1],
      ['Lynyrd Skynyrd', 1],
      ['Heart', 1],
      ['The Doors', 1],
      ['Creedence Clearwater Revival', 1],
      ['Jimi Hendrix', 1],

      ['The Strokes', 2],
      ['The White Stripes', 2],
      ['Kings of Leon', 2],
      ['Vampire Weekend', 2],
      ['Franz Ferdinand', 2],
      ['Kaiser Chiefs', 2],
      ['Bloc Party', 2],
      ['Interpol', 2],
      ['The National', 2],
      ['The Shins', 2],
      ['Death Cab for Cutie', 2],
      ['Modest Mouse', 2],
      ['Yeah Yeah Yeahs', 2],
      ['The Black Keys', 2],
      ['Cage The Elephant', 2],
      ['Foster The People', 2],
      ['Two Door Cinema Club', 2],
      ['Phoenix', 2],
      ['MGMT', 2],
      ['Empire of the Sun', 2],
      ['Tame Impala', 2],
      ['Glass Animals', 2],
      ['alt-J', 2],
      ['Wolf Alice', 2],
      ['Royal Blood', 2],
      ['Catfish and the Bottlemen', 2],
      ['The 1975', 2],
      ['Sam Fender', 2],
      ['Fontaines D.C.', 2],
      ['IDLES', 2],
      ['Pixies', 2],
      ['Sonic Youth', 2],
      ['Talking Heads', 2],
      ['Joy Division', 2],
      ['The Clash', 2],
      ['Ramones', 2],
      ['Sex Pistols', 2],
      ['The Smiths', 2],
      ['New Order', 2],
      ['Depeche Mode', 2],
      ['Nine Inch Nails', 2],
      ['Rage Against the Machine', 2],
      ['System of a Down', 2],
      ['TOOL', 2],
      ['Deftones', 2],
      ['Incubus', 2],
      ['Sublime', 2],
      ['Third Eye Blind', 2],
      ['Goo Goo Dolls', 2],
      ['Matchbox Twenty', 2],
      ['Counting Crows', 2],
      ['Collective Soul', 2],
      ['Bush', 2],
      ['Everclear', 2],
      ['Semisonic', 2],
      ['My Chemical Romance', 2],
      ['Fall Out Boy', 2],
      ['Panic! At The Disco', 2],
      ['Paramore', 2],
      ['Jimmy Eat World', 2],
      ['Taking Back Sunday', 2],
      ['Brand New', 2],

      ['Big Thief', 3],
      ['Alvvays', 3],
      ['Snail Mail', 3],
      ['Soccer Mommy', 3],
      ['Japanese Breakfast', 3],
      ['Beach House', 3],
      ['Slowdive', 3],
      ['My Bloody Valentine', 3],
      ['Ride', 3],
      ['Cocteau Twins', 3],
      ['Mazzy Star', 3],
      ['Yo La Tengo', 3],
      ['Built to Spill', 3],
      ['Pavement', 3],
      ['Guided By Voices', 3],
      ['Dinosaur Jr.', 3],
      ['Sebadoh', 3],
      ['Superchunk', 3],
      ['Slint', 3],
      ['Fugazi', 3],
      ['At the Drive-In', 3],
      ['The Mars Volta', 3],
      ['black midi', 3],
      ['Black Country, New Road', 3],
      ['Squid', 3],
      ['Dry Cleaning', 3],
      ['Shame', 3],
      ['Turnstile', 3],
      ['Wednesday', 3],
      ['MJ Lenderman', 3],
      ['Duster', 3],
      ['Unwound', 3],
      ['Swervedriver', 3],
      ['Lush', 3],
      ['Chapterhouse', 3],
    ],
  },

  {
    id: 'anime',
    perArtist: 60,
    color: '#E8672A',
    name: 'Anime',
    code: 'ANI',
    blurb: 'Openings, endings and inserts',
    // Only tracks that match the AnimeThemes.moe catalog are kept, and each one
    // carries its source ("Kimetsu no Yaiba OP1"). The cap is high because the
    // theme match is the real filter: an anisong specialist's catalog is dense
    // with themes, and everything else falls out.
    themeMatch: true,
    nativeScript: true,
    // Fetch by resolved artistId, not by name search: one-word acts like LiSA,
    // Eve and FLOW drown in same-name noise otherwise. See searchArtistById.
    lookupArtist: true,
    artists: [
      ['LiSA', 1], ['Aimer', 1], ['Kenshi Yonezu', 1], ['YOASOBI', 1],
      ['Ado', 1], ['Eve', 1], ['RADWIMPS', 1], ['King Gnu', 1],
      ['Official HIGE DANdism', 1], ['Mrs. GREEN APPLE', 1], ['Vaundy', 1],
      ['ONE OK ROCK', 1], ['UVERworld', 1], ['FLOW', 1],
      ['ASIAN KUNG-FU GENERATION', 1], ['Ikimonogakari', 1],
      ['Porno Graffitti', 1], ['BUMP OF CHICKEN', 1], ['Creepy Nuts', 1],
      ['milet', 1], ['Gen Hoshino', 1], ['back number', 1], ['Fujii Kaze', 1],
      ['Tatsuya Kitani', 1], ['SiM', 1], ['Linked Horizon', 1],
      ['MAN WITH A MISSION', 1], ['SPYAIR', 1], ['EGOIST', 1],
      ['Yoko Takahashi', 1], ['Hiroyuki Sawano', 1], ['SawanoHiroyuki[nZk]', 1],

      ['KANA-BOON', 2], ['BURNOUT SYNDROMES', 2], ['sumika', 2],
      ['Vickeblanka', 2], ['ClariS', 2], ['fripSide', 2], ['Eir Aoi', 2],
      ['ReoNa', 2], ['ASCA', 2], ['Konomi Suzuki', 2], ['Luna Haruna', 2],
      ['Nana Mizuki', 2], ["May'n", 2], ['angela', 2], ['GRANRODEO', 2],
      ['JAM Project', 2], ['T.M.Revolution', 2], ['Masaaki Endoh', 2],
      ['Ichirou Mizuki', 2], ['Megumi Hayashibara', 2], ['Maaya Sakamoto', 2],
      ['Kalafina', 2], ['supercell', 2], ['Aqours', 2], ["μ's", 2],
      ['Roselia', 2], ["Poppin'Party", 2], ['ZUTOMAYO', 2], ['Reol', 2],
      ['MAXIMUM THE HORMONE', 2], ["L'Arc~en~Ciel", 2], ['Do As Infinity', 2],
      ['abingdon boys school', 2], ['HOME MADE Kazoku', 2], ['ORANGE RANGE', 2],
      ['BEAT CRUSADERS', 2], ['NICO Touches the Walls', 2], ['Sambomaster', 2],
      ['Aqua Timez', 2], ['YUI', 2], ['miwa', 2], ['SCANDAL', 2],
      ['Stereopony', 2], ['Galileo Galilei', 2], ['Goose house', 2],
      ['Uru', 2], ['Sukima Switch', 2], ['Little Glee Monster', 2],
      ['UNISON SQUARE GARDEN', 2], ['BLUE ENCOUNT', 2],
      ['THE ORAL CIGARETTES', 2], ['04 Limited Sazabys', 2],
      ['Fear, and Loathing in Las Vegas', 2], ['coldrain', 2],
      ['Ling tosite sigure', 2], ['TK from Ling tosite sigure', 2],
      ['amazarashi', 2], ['[Alexandros]', 2], ['Novelbright', 2],
      ['PEOPLE 1', 2], ['ano', 2], ['Cö shu Nie', 2], ['Who-ya Extended', 2],
      ['MYTH & ROID', 2], ['Yorushika', 2],

      ['OxT', 3], ['Masayoshi Oishi', 3], ['ZAQ', 3], ['GARNiDELiA', 3],
      ['Mili', 3], ['Kishida Kyoudan & The Akeboshi Rockets', 3],
      ['ChouCho', 3], ['Lia', 3], ['See-Saw', 3], ['FictionJunction', 3],
      ['TrySail', 3], ['Sphere', 3], ['Ai Higuchi', 3], ['sajou no hana', 3],
      ['Wagakki Band', 3], ['yama', 3], ['Tani Yuuki', 3], ['Omoinotake', 3],
      ['Hitsujibungaku', 3], ['Kessoku Band', 3], ['Aina The End', 3],
      ['Anonymouz', 3], ['Sangatsu no Phantasia', 3], ['halca', 3],
      ['Minami', 3], ['Mafumafu', 3], ['Kankaku Piero', 3],
      ['Survive Said The Prophet', 3], ['DISH//', 3], ['Saucy Dog', 3],
      ['Chico with HoneyWorks', 3], ['HoneyWorks', 3], ['TRUE', 3],
      ['yanaginagi', 3], ['Minori Chihara', 3], ['Yui Horie', 3],
      ['KOTOKO', 3], ['Rie fu', 3], ['High and Mighty Color', 3],
      ['FLOW-BACK', 3],

      ['Sayuri', 3], ['Nanawo Akari', 3], ['Aimyon', 2], ['JUDY AND MARY', 2],
      ['Hikaru Utada', 1], ['YUKI', 2], ['the pillows', 2], ['the peggies', 3],
      ['MY FIRST STORY', 2], ['HYDE', 2], ['TUYU', 3], ['Myuk', 3],
      ['fhana', 3], ['nano', 3], ['Yuki Kajiura', 2], ['ALI', 3],
      ['Queen Bee', 2], ['Yoh Kamiyama', 3], ['Keina Suda', 3],
      ['Hitorie', 3], ['Miyuna', 3], ['Luck Life', 3],
      ['Hironobu Kageyama', 2], ['Masatoshi Ono', 3], ['Yuzu', 2],
      ['WANDS', 2], ['Maki Ohguro', 3], ['BAAD', 3], ['FIELD OF VIEW', 3],
      ['ZARD', 2], ["B'z", 2], ['Mai Kuraki', 2], ['GARNET CROW', 3],
      ['TWO-MIX', 3], ['m.o.v.e', 3], ['Mikuni Shimokawa', 3],
      ['Masami Okui', 3], ['Shoko Nakagawa', 3], ['AKINO from bless4', 3],
      ['CHEMISTRY', 3], ['Nami Tamaki', 3], ['Fujifabric', 3], ['SID', 2],
      ['Nightmare', 3], ['Anna Tsuchiya', 3], ['Tommy heavenly6', 3],
      ['DOES', 3],
      ['MINMI', 3], ['Nujabes', 3], ['Takanori Nishikawa', 3],
      ['Yousei Teikoku', 3], ['Machico', 3], ['Riko Azuna', 3],
      ['Chiai Fujikawa', 3], ['MADKID', 3], ['RAISE A SUILEN', 3],
      ['flumpool', 3], ['Ryokuoushoku Shakai', 2], ['Tainaka Sachi', 3],
    ],
  },

  {
    id: 'kpop',
    perArtist: 16,
    color: '#BC5FE3',
    name: 'K-Pop',
    code: 'KOR',
    blurb: 'Idols, soloists and the Hallyu wave',
    nativeScript: true,
    artists: [
      ['BTS', 1],
      ['BLACKPINK', 1],
      ['TWICE', 1],
      ['EXO', 1],
      ['Red Velvet', 1],
      ['SEVENTEEN', 1],
      ['Stray Kids', 1],
      ['NCT 127', 1],
      ['NCT DREAM', 1],
      ['aespa', 1],
      ['ITZY', 1],
      ['IVE', 1],
      ['NewJeans', 1],
      ['LE SSERAFIM', 1],
      ['(G)I-DLE', 1],
      ['TOMORROW X TOGETHER', 1],
      ['ENHYPEN', 1],
      ['ATEEZ', 1],
      ['MONSTA X', 1],
      ['GOT7', 1],
      ['BIGBANG', 1],
      ['2NE1', 1],
      ["Girls' Generation", 1],
      ['SHINee', 1],
      ['SUPER JUNIOR', 1],
      ['Wonder Girls', 1],
      ['IU', 1],
      ['PSY', 1],
      ['G-DRAGON', 1],
      ['TAEYANG', 1],

      ['CL', 2],
      ['SUNMI', 2],
      ['HyunA', 2],
      ['CHUNG HA', 2],
      ['TAEYEON', 2],
      ['JENNIE', 2],
      ['JISOO', 2],
      ['ROSÉ', 2],
      ['LISA', 2],
      ['Jung Kook', 2],
      ['Jimin', 2],
      ['V', 2],
      ['j-hope', 2],
      ['RM', 2],
      ['Agust D', 2],
      ['ZICO', 2],
      ['Jay Park', 2],
      ['DEAN', 2],
      ['Crush', 2],
      ['HEIZE', 2],
      ['Zion.T', 2],
      ['BAEKHYUN', 2],
      ['KAI', 2],
      ['TAEMIN', 2],
      ['MAMAMOO', 2],
      ['GFRIEND', 2],
      ['OH MY GIRL', 2],
      ['WJSN', 2],
      ['EVERGLOW', 2],
      ['Dreamcatcher', 2],
      ['LOONA', 2],
      ['fromis_9', 2],
      ['STAYC', 2],
      ['Kep1er', 2],
      ['NMIXX', 2],
      ['Apink', 2],
      ['T-ARA', 2],
      ['KARA', 2],
      ['Rain', 2],
      ['BoA', 2],
      ['SISTAR', 2],
      ['4MINUTE', 2],
      ['miss A', 2],
      ['f(x)', 2],
      ['After School', 2],
      ['Brown Eyed Girls', 2],
      ['TVXQ!', 2],
      ['HIGHLIGHT', 2],
      ['B1A4', 2],
      ['INFINITE', 2],
      ['VIXX', 2],
      ['BTOB', 2],
      ['Block B', 2],
      ['WINNER', 2],
      ['iKON', 2],

      ['DAY6', 3],
      ['N.Flying', 3],
      ['The Rose', 3],
      ['Xdinary Heroes', 3],
      ['Epik High', 3],
      ['Dynamic Duo', 3],
      ['Beenzino', 3],
      ['pH-1', 3],
      ['LEE HI', 3],
      ['AKMU', 3],
      ['BOL4', 3],
      ['10CM', 3],
      ['Paul Kim', 3],
      ['SAM KIM', 3],
      ['JANNABI', 3],
      ['Standing Egg', 3],
      ['Younha', 3],
      ['Baek Yerin', 3],
      ['Sunwoojunga', 3],
      ['CHEEZE', 3],
      ['Car, the garden', 3],
      ['Nell', 3],
      ['Hyukoh', 3],
      ['SE SO NEON', 3],
      ['Silica Gel', 3],
      ['ADOY', 3],
      ['Lucy', 3],
      ['QWER', 3],
      ['BIBI', 3],
      ['Colde', 3],
      ['offonoff', 3],
      ['GIRIBOY', 3],
      ['Woo', 3],
      ['Sokodomo', 3],
      ['Balming Tiger', 3],
    ],
  },

  {
    id: 'vgm',
    perArtist: 40,
    color: '#4ACF8B',
    name: 'Game Music',
    code: 'VGM',
    blurb: 'Chiptune, boss themes and open worlds',
    // The store credits arrangers, orchestras and sound teams rather than the
    // named composer, so the artist-name gate has to come off.
    nativeScript: true,
    artists: [
      ['Koji Kondo', 1], ['Nobuo Uematsu', 1], ['Yasunori Mitsuda', 1], ['Motoi Sakuraba', 1],
      ['Shoji Meguro', 1], ['Yoko Shimomura', 1], ['Keiichi Okabe', 1], ['Toby Fox', 1],
      ['Mick Gordon', 1], ['Austin Wintory', 1], ['Jesper Kyd', 1], ['Jeremy Soule', 1],
      ['Martin O\'Donnell', 1], ['Gareth Coker', 1], ['Darren Korb', 1], ['Lena Raine', 1],
      ['Grant Kirkhope', 2], ['David Wise', 2], ['Yuzo Koshiro', 2], ['Hirokazu Tanaka', 2],
      ['Junichi Masuda', 2], ['Go Ichinose', 2], ['Kenji Ito', 2], ['Hitoshi Sakimoto', 2],
      ['Masashi Hamauzu', 2], ['Naoshi Mizuta', 2], ['Yoko Kanno', 2], ['Akira Yamaoka', 2],
      ['Tomoya Ohtani', 2], ['Jun Senoue', 2], ['Michiru Yamane', 2], ['Kow Otani', 2],
      ['Christopher Larkin', 2], ['Disasterpeace', 2], ['C418', 2], ['Lena Chappelle', 2],
      ['Inon Zur', 3], ['Bear McCreary', 3], ['Sarah Schachner', 3], ['Petri Alanko', 3],
      ['Olivier Deriviere', 3], ['Ben Prunty', 3], ['Laura Shigihara', 3],
      ['Kumi Tanioka', 3], ['Manami Matsumae', 3], ['Takeshi Abo', 3],
      ['Koichi Sugiyama', 2], ['Masayoshi Soken', 2], ['Yuka Kitamura', 2],
      ['Go Shiina', 2], ['Masafumi Takada', 2], ['Norihiko Hibino', 3],
      ['Keiki Kobayashi', 3], ['Kenji Yamamoto', 3], ['Kazumi Totaka', 3],
      ['Hideki Naganuma', 2], ['Ippo Yamada', 3], ['Marcin Przybylowicz', 2],
      ['Piotr Musial', 3], ['Borislav Slavov', 3], ['Jack Wall', 3],
      ['Sam Hulick', 3], ['Cris Velasco', 3], ['Winifred Phillips', 3],
      ['Danny Baranowsky', 2], ['Anamanaguchi', 2], ['Chipzel', 3],
      ['Lifeformed', 3], ['ConcernedApe', 1], ['Scott Lloyd Shelly', 2],
    ],
  },
];

export const GENRE_BY_ID = Object.fromEntries(GENRES.map((g) => [g.id, g]));
