// Song catalog. Each entry is [title, artist].
// These strings are sent verbatim to the iTunes Search API, so keep them close
// to how the track is actually credited on Apple Music. Punctuation is
// normalized away before matching, so straight quotes are fine.
//
// To add a pack: append an object with a unique `id` and 20+ tracks, then run
//   node tools/build-index.mjs
// to resolve them to real previews. Packs may set `looseArtist: true` when the
// catalog credits a composer but the store credits a performer.

export const PACKS = [
  {
    id: 'pop', name: 'Pop Classics', emoji: '🎤',
    blurb: 'Chart-toppers from the 80s to now',
    tracks: [
      ['Billie Jean', 'Michael Jackson'],
      ['Like a Prayer', 'Madonna'],
      ['Girls Just Want to Have Fun', 'Cyndi Lauper'],
      ['Take On Me', 'a-ha'],
      ['Wannabe', 'Spice Girls'],
      ['I Want It That Way', 'Backstreet Boys'],
      ['...Baby One More Time', 'Britney Spears'],
      ['Genie in a Bottle', 'Christina Aguilera'],
      ['Torn', 'Natalie Imbruglia'],
      ['MMMBop', 'Hanson'],
      ['Toxic', 'Britney Spears'],
      ['Complicated', 'Avril Lavigne'],
      ['Since U Been Gone', 'Kelly Clarkson'],
      ['Umbrella', 'Rihanna'],
      ['Poker Face', 'Lady Gaga'],
      ['Bad Romance', 'Lady Gaga'],
      ['Rolling in the Deep', 'Adele'],
      ['Call Me Maybe', 'Carly Rae Jepsen'],
      ['Somebody That I Used to Know', 'Gotye'],
      ['Shake It Off', 'Taylor Swift'],
      ['Uptown Funk', 'Mark Ronson'],
      ['Shape of You', 'Ed Sheeran'],
      ['Blinding Lights', 'The Weeknd'],
      ['Levitating', 'Dua Lipa'],
      ['drivers license', 'Olivia Rodrigo'],
      ['As It Was', 'Harry Styles'],
      ['Flowers', 'Miley Cyrus'],
      ['Espresso', 'Sabrina Carpenter'],
      ['Firework', 'Katy Perry'],
      ['Wake Me Up', 'Avicii'],
    ],
  },
  {
    id: 'rock', name: 'Rock & Alternative', emoji: '🎸',
    blurb: 'Riffs, arenas and college radio',
    tracks: [
      ['Bohemian Rhapsody', 'Queen'],
      ['Stairway to Heaven', 'Led Zeppelin'],
      ['Hotel California', 'Eagles'],
      ['Back in Black', 'AC/DC'],
      ["Sweet Child O'Mine", "Guns N' Roses"],
      ['Dream On', 'Aerosmith'],
      ['Free Bird', 'Lynyrd Skynyrd'],
      ['Barracuda', 'Heart'],
      ['Comfortably Numb', 'Pink Floyd'],
      ['Every Breath You Take', 'The Police'],
      ['With or Without You', 'U2'],
      ['Smells Like Teen Spirit', 'Nirvana'],
      ['Black Hole Sun', 'Soundgarden'],
      ['Under the Bridge', 'Red Hot Chili Peppers'],
      ['Creep', 'Radiohead'],
      ['Karma Police', 'Radiohead'],
      ['Zombie', 'The Cranberries'],
      ['Wonderwall', 'Oasis'],
      ['Where Is My Mind?', 'Pixies'],
      ['Killing in the Name', 'Rage Against the Machine'],
      ['Everlong', 'Foo Fighters'],
      ['Last Nite', 'The Strokes'],
      ['Seven Nation Army', 'The White Stripes'],
      ['Take Me Out', 'Franz Ferdinand'],
      ['Mr. Brightside', 'The Killers'],
      ["Don't Stop Believin'", 'Journey'],
      ["Livin' On a Prayer", 'Bon Jovi'],
      ['Song 2', 'Blur'],
      ['Bitter Sweet Symphony', 'The Verve'],
      ['Do I Wanna Know?', 'Arctic Monkeys'],
    ],
  },
  {
    id: 'hiphop', name: 'Hip-Hop & Rap', emoji: '🎧',
    blurb: 'Boom bap to trap',
    tracks: [
      ['The Message', 'Grandmaster Flash & The Furious Five'],
      ['Fight the Power', 'Public Enemy'],
      ['Juicy', 'The Notorious B.I.G.'],
      ['Big Poppa', 'The Notorious B.I.G.'],
      ['California Love', '2Pac'],
      ['N.Y. State of Mind', 'Nas'],
      ['Shook Ones, Pt. II', 'Mobb Deep'],
      ['Triumph', 'Wu-Tang Clan'],
      ['Sabotage', 'Beastie Boys'],
      ['Hey Ya!', 'OutKast'],
      ['Ms. Jackson', 'OutKast'],
      ['Lose Yourself', 'Eminem'],
      ['In Da Club', '50 Cent'],
      ['Jesus Walks', 'Kanye West'],
      ['Stronger', 'Kanye West'],
      ['Empire State of Mind', 'JAY-Z'],
      ['99 Problems', 'JAY-Z'],
      ['m.A.A.d city', 'Kendrick Lamar'],
      ['Alright', 'Kendrick Lamar'],
      ['HUMBLE.', 'Kendrick Lamar'],
      ['Bad and Boujee', 'Migos'],
      ['SICKO MODE', 'Travis Scott'],
      ['Old Town Road', 'Lil Nas X'],
      ['Nonstop', 'Drake'],
      ['XO Tour Llif3', 'Lil Uzi Vert'],
      ['Rap God', 'Eminem'],
      ['Still D.R.E.', 'Dr. Dre'],
      ['Regulate', 'Warren G'],
      ['Passin Me By', 'The Pharcyde'],
      ['Aruarian Dance', 'Nujabes'],
    ],
  },
  {
    id: 'rnb', name: 'R&B & Soul', emoji: '💜',
    blurb: 'Motown, quiet storm and neo-soul',
    tracks: [
      ['My Girl', 'The Temptations'],
      ['I Heard It Through the Grapevine', 'Marvin Gaye'],
      ["What's Going On", 'Marvin Gaye'],
      ['Respect', 'Aretha Franklin'],
      ['Superstition', 'Stevie Wonder'],
      ["Ain't No Mountain High Enough", 'Marvin Gaye'],
      ["Let's Stay Together", 'Al Green'],
      ["(Sittin' On) the Dock of the Bay", 'Otis Redding'],
      ['I Will Always Love You', 'Whitney Houston'],
      ['End of the Road', 'Boyz II Men'],
      ['No Scrubs', 'TLC'],
      ['Waterfalls', 'TLC'],
      ['Say My Name', "Destiny's Child"],
      ['Crazy in Love', 'Beyoncé'],
      ['Doo Wop (That Thing)', 'Ms. Lauryn Hill'],
      ['Untitled (How Does It Feel)', "D'Angelo"],
      ['Cranes in the Sky', 'Solange'],
      ['Best Part', 'Daniel Caesar'],
      ['Location', 'Khalid'],
      ['Redbone', 'Childish Gambino'],
      ['Thinkin Bout You', 'Frank Ocean'],
      ['Nights', 'Frank Ocean'],
      ['Snooze', 'SZA'],
      ['Adorn', 'Miguel'],
      ['Love On the Brain', 'Rihanna'],
      ['Sure Thing', 'Miguel'],
      ['Kiss From a Rose', 'Seal'],
      ['Rock With You', 'Michael Jackson'],
    ],
  },
  {
    id: 'country', name: 'Country & Americana', emoji: '🤠',
    blurb: 'Nashville, outlaw and roots',
    tracks: [
      ['Ring of Fire', 'Johnny Cash'],
      ['Jolene', 'Dolly Parton'],
      ['9 to 5', 'Dolly Parton'],
      ['Take Me Home, Country Roads', 'John Denver'],
      ['On the Road Again', 'Willie Nelson'],
      ['He Stopped Loving Her Today', 'George Jones'],
      ['Friends in Low Places', 'Garth Brooks'],
      ['Achy Breaky Heart', 'Billy Ray Cyrus'],
      ['Man! I Feel Like a Woman!', 'Shania Twain'],
      ["You're Still the One", 'Shania Twain'],
      ['Wide Open Spaces', 'The Chicks'],
      ['Before He Cheats', 'Carrie Underwood'],
      ['Chicken Fried', 'Zac Brown Band'],
      ['Wagon Wheel', 'Darius Rucker'],
      ['Cruise', 'Florida Georgia Line'],
      ['Tennessee Whiskey', 'Chris Stapleton'],
      ['The Gambler', 'Kenny Rogers'],
      ['Fast Car', 'Luke Combs'],
      ['Whiskey Glasses', 'Morgan Wallen'],
      ['Follow Your Arrow', 'Kacey Musgraves'],
      ['Space Cowboy', 'Kacey Musgraves'],
      ['White Horse', 'Taylor Swift'],
      ['I Walk the Line', 'Johnny Cash'],
      ['Crazy', 'Patsy Cline'],
      ['Rhinestone Cowboy', 'Glen Campbell'],
      ["Coal Miner's Daughter", 'Loretta Lynn'],
      ['Colder Weather', 'Zac Brown Band'],
      ['Need You Now', 'Lady A'],
    ],
  },
  {
    id: 'metal', name: 'Metal', emoji: '🤘',
    blurb: 'NWOBHM, thrash, nu, djent',
    tracks: [
      ['Paranoid', 'Black Sabbath'],
      ['Iron Man', 'Black Sabbath'],
      ['Ace of Spades', 'Motörhead'],
      ['The Trooper', 'Iron Maiden'],
      ['Run to the Hills', 'Iron Maiden'],
      ['Painkiller', 'Judas Priest'],
      ['Master of Puppets', 'Metallica'],
      ['Enter Sandman', 'Metallica'],
      ['One', 'Metallica'],
      ['Holy Wars... The Punishment Due', 'Megadeth'],
      ['Raining Blood', 'Slayer'],
      ['Chop Suey!', 'System of a Down'],
      ['Toxicity', 'System of a Down'],
      ['Freak On a Leash', 'Korn'],
      ['Duality', 'Slipknot'],
      ['Psychosocial', 'Slipknot'],
      ['Down With the Sickness', 'Disturbed'],
      ['Bodies', 'Drowning Pool'],
      ['Schism', 'TOOL'],
      ['Bleed', 'Meshuggah'],
      ['CAFO', 'Animals as Leaders'],
      ['Bulls On Parade', 'Rage Against the Machine'],
      ['Walk', 'Pantera'],
      ['Cowboys From Hell', 'Pantera'],
      ['Hail to the King', 'Avenged Sevenfold'],
      ['Bat Country', 'Avenged Sevenfold'],
      ['In Waves', 'Trivium'],
      ['Blinded By Fear', 'At the Gates'],
      ['Pull Me Under', 'Dream Theater'],
      ['Bleed It Out', 'Linkin Park'],
    ],
  },
  {
    id: 'punk', name: 'Punk & Emo', emoji: '🖤',
    blurb: 'Three chords, eyeliner optional',
    tracks: [
      ['Blitzkrieg Bop', 'Ramones'],
      ['Anarchy in the U.K.', 'Sex Pistols'],
      ['London Calling', 'The Clash'],
      ['Should I Stay or Should I Go', 'The Clash'],
      ['Basket Case', 'Green Day'],
      ['American Idiot', 'Green Day'],
      ['Self Esteem', 'The Offspring'],
      ['All the Small Things', 'blink-182'],
      ["What's My Age Again?", 'blink-182'],
      ['Dammit', 'blink-182'],
      ["Sugar, We're Goin Down", 'Fall Out Boy'],
      ['Thnks fr th Mmrs', 'Fall Out Boy'],
      ['Welcome to the Black Parade', 'My Chemical Romance'],
      ['Helena', 'My Chemical Romance'],
      ['Teenagers', 'My Chemical Romance'],
      ['Misery Business', 'Paramore'],
      ['Still Into You', 'Paramore'],
      ['I Write Sins Not Tragedies', 'Panic! At the Disco'],
      ['The Middle', 'Jimmy Eat World'],
      ['Ocean Avenue', 'Yellowcard'],
      ['Flagpole Sitta', 'Harvey Danger'],
      ['Screaming Infidelities', 'Dashboard Confessional'],
      ['Rebel Girl', 'Bikini Kill'],
      ['Holiday in Cambodia', 'Dead Kennedys'],
      ['Linoleum', 'NOFX'],
      ['I Miss You', 'blink-182'],
      ['Ohio Is for Lovers', 'Hawthorne Heights'],
      ['The Anthem', 'Good Charlotte'],
    ],
  },
  {
    id: 'edm', name: 'Electronic & Dance', emoji: '🔊',
    blurb: 'House, techno, DnB, big room',
    tracks: [
      ['Blue Monday', 'New Order'],
      ['Around the World', 'Daft Punk'],
      ['One More Time', 'Daft Punk'],
      ['Da Funk', 'Daft Punk'],
      ['Born Slippy .NUXX', 'Underworld'],
      ['Firestarter', 'The Prodigy'],
      ['Breathe', 'The Prodigy'],
      ["Block Rockin' Beats", 'The Chemical Brothers'],
      ['Praise You', 'Fatboy Slim'],
      ['Right Here, Right Now', 'Fatboy Slim'],
      ['Windowlicker', 'Aphex Twin'],
      ['Xtal', 'Aphex Twin'],
      ['Midnight City', 'M83'],
      ['Levels', 'Avicii'],
      ['Titanium', 'David Guetta'],
      ['Animals', 'Martin Garrix'],
      ['Scary Monsters and Nice Sprites', 'Skrillex'],
      ['Bangarang', 'Skrillex'],
      ['Clarity', 'Zedd'],
      ["Ghosts 'n' Stuff", 'deadmau5'],
      ['Strobe', 'deadmau5'],
      ['Opus', 'Eric Prydz'],
      ['Language', 'Porter Robinson'],
      ['Shelter', 'Porter Robinson'],
      ['Roygbiv', 'Boards of Canada'],
      ['Teardrop', 'Massive Attack'],
      ['Music Sounds Better With You', 'Stardust'],
      ['Innerbloom', 'RÜFÜS DU SOL'],
      ['Sandstorm', 'Darude'],
      ['Chime', 'Orbital'],
    ],
  },
  {
    id: 'jazz', name: 'Jazz Standards', emoji: '🎺',
    blurb: 'Bebop, cool, modal, fusion',
    tracks: [
      ['Take Five', 'The Dave Brubeck Quartet'],
      ['So What', 'Miles Davis'],
      ['Blue in Green', 'Miles Davis'],
      ['Freddie Freeloader', 'Miles Davis'],
      ['My Favorite Things', 'John Coltrane'],
      ['Giant Steps', 'John Coltrane'],
      ['Naima', 'John Coltrane'],
      ["Round Midnight", 'Thelonious Monk'],
      ['Blue Monk', 'Thelonious Monk'],
      ['Sing, Sing, Sing', 'Benny Goodman'],
      ['Take the A Train', 'Duke Ellington'],
      ['Fly Me to the Moon', 'Frank Sinatra'],
      ['What a Wonderful World', 'Louis Armstrong'],
      ['Summertime', 'Ella Fitzgerald'],
      ['Feeling Good', 'Nina Simone'],
      ['Sinnerman', 'Nina Simone'],
      ['Cantaloupe Island', 'Herbie Hancock'],
      ['Watermelon Man', 'Herbie Hancock'],
      ['Chameleon', 'Herbie Hancock'],
      ['Maiden Voyage', 'Herbie Hancock'],
      ["Moanin'", 'Art Blakey & The Jazz Messengers'],
      ['Song for My Father', 'Horace Silver'],
      ['Birdland', 'Weather Report'],
      ['Spain', 'Chick Corea'],
      ['Autumn Leaves', 'Cannonball Adderley'],
      ['The Girl from Ipanema', 'Stan Getz'],
      ['St. Thomas', 'Sonny Rollins'],
      ['Strange Fruit', 'Billie Holiday'],
    ],
  },
  {
    id: 'classical', name: 'Classical', emoji: '🎻', looseArtist: true,
    blurb: 'Baroque through the Romantics',
    tracks: [
      ['Symphony No. 5 in C Minor', 'Ludwig van Beethoven'],
      ['Ode to Joy', 'Ludwig van Beethoven'],
      ['Moonlight Sonata', 'Ludwig van Beethoven'],
      ['Für Elise', 'Ludwig van Beethoven'],
      ['Eine kleine Nachtmusik', 'Wolfgang Amadeus Mozart'],
      ['Symphony No. 40 in G Minor', 'Wolfgang Amadeus Mozart'],
      ['Rondo alla Turca', 'Wolfgang Amadeus Mozart'],
      ['Lacrimosa', 'Wolfgang Amadeus Mozart'],
      ['The Four Seasons: Spring', 'Antonio Vivaldi'],
      ['Toccata and Fugue in D Minor', 'Johann Sebastian Bach'],
      ['Air On the G String', 'Johann Sebastian Bach'],
      ['Brandenburg Concerto No. 3', 'Johann Sebastian Bach'],
      ['Canon in D', 'Johann Pachelbel'],
      ['Clair de lune', 'Claude Debussy'],
      ['Gymnopédie No. 1', 'Erik Satie'],
      ['Boléro', 'Maurice Ravel'],
      ['The Blue Danube', 'Johann Strauss II'],
      ['In the Hall of the Mountain King', 'Edvard Grieg'],
      ['1812 Overture', 'Pyotr Ilyich Tchaikovsky'],
      ['Swan Lake', 'Pyotr Ilyich Tchaikovsky'],
      ['Dance of the Sugar Plum Fairy', 'Pyotr Ilyich Tchaikovsky'],
      ['Also sprach Zarathustra', 'Richard Strauss'],
      ['Ride of the Valkyries', 'Richard Wagner'],
      ['The Rite of Spring', 'Igor Stravinsky'],
      ['O Fortuna', 'Carl Orff'],
      ['Nocturne in E-Flat Major, Op. 9 No. 2', 'Frédéric Chopin'],
      ['Hungarian Rhapsody No. 2', 'Franz Liszt'],
      ['Adagio for Strings', 'Samuel Barber'],
    ],
  },
  {
    id: 'kpop', name: 'K-Pop', emoji: '🇰🇷',
    blurb: 'Gen 1 through gen 5',
    tracks: [
      ['Gee', "Girls' Generation"],
      ['I Got a Boy', "Girls' Generation"],
      ['Fantastic Baby', 'BIGBANG'],
      ['Gangnam Style', 'PSY'],
      ['I Am the Best', '2NE1'],
      ['Growl', 'EXO'],
      ['Cheer Up', 'TWICE'],
      ['TT', 'TWICE'],
      ['BOOMBAYAH', 'BLACKPINK'],
      ['DDU-DU DDU-DU', 'BLACKPINK'],
      ['Kill This Love', 'BLACKPINK'],
      ['Blood Sweat & Tears', 'BTS'],
      ['DNA', 'BTS'],
      ['Dynamite', 'BTS'],
      ['Red Flavor', 'Red Velvet'],
      ['Psycho', 'Red Velvet'],
      ['WANNABE', 'ITZY'],
      ["God's Menu", 'Stray Kids'],
      ['Next Level', 'aespa'],
      ['Savage', 'aespa'],
      ['Hype Boy', 'NewJeans'],
      ['Ditto', 'NewJeans'],
      ['Super Shy', 'NewJeans'],
      ['LOVE DIVE', 'IVE'],
      ['ANTIFRAGILE', 'LE SSERAFIM'],
      ['Queencard', '(G)I-DLE'],
      ['Cupid', 'FIFTY FIFTY'],
      ['VERY NICE', 'SEVENTEEN'],
      ['Kick It', 'NCT 127'],
      ['Cherry Bomb', 'NCT 127'],
    ],
  },
  {
    id: 'jpop', name: 'J-Pop & City Pop', emoji: '🗼',
    blurb: 'Showa nights and modern Japan',
    tracks: [
      ['Plastic Love', 'Mariya Takeuchi'],
      ['Stay With Me', 'Miki Matsubara'],
      ['Ride On Time', 'Tatsuro Yamashita'],
      ['Sparkle', 'Tatsuro Yamashita'],
      ['Magic Ways', 'Tatsuro Yamashita'],
      ['Kimi ni Mune Kyun', 'Yellow Magic Orchestra'],
      ['Rydeen', 'Yellow Magic Orchestra'],
      ['Sukiyaki', 'Kyu Sakamoto'],
      ['First Love', 'Utada Hikaru'],
      ['Automatic', 'Utada Hikaru'],
      ['Lemon', 'Kenshi Yonezu'],
      ['KICK BACK', 'Kenshi Yonezu'],
      ['Pretender', 'Official HIGE DANdism'],
      ['Subtitle', 'Official HIGE DANdism'],
      ['Yoru ni Kakeru', 'YOASOBI'],
      ['Idol', 'YOASOBI'],
      ['Marigold', 'Aimyon'],
      ['Zenzenzense', 'RADWIMPS'],
      ['Uchiage Hanabi', 'DAOKO'],
      ['Aitai', 'Fujii Kaze'],
      ['Shinunoga E-Wa', 'Fujii Kaze'],
      ['Odo', 'Ado'],
      ['Usseewa', 'Ado'],
      ['Senbonzakura', 'Hatsune Miku'],
      ['Tsunami', 'Southern All Stars'],
      ['Linda Linda', 'THE BLUE HEARTS'],
      ['Mayonaka no Door', 'Miki Matsubara'],
      ['Cry Baby', 'Official HIGE DANdism'],
    ],
  },
  {
    id: 'anime', name: 'Anime Openings', emoji: '⛩️',
    blurb: 'Ninety seconds of pure adrenaline',
    tracks: [
      ['CHA-LA HEAD-CHA-LA', 'Hironobu Kageyama'],
      ["A Cruel Angel's Thesis", 'Yoko Takahashi'],
      ['Tank!', 'Seatbelts'],
      ['Rewrite', 'ASIAN KUNG-FU GENERATION'],
      ['Haruka Kanata', 'ASIAN KUNG-FU GENERATION'],
      ['Guren no Yumiya', 'Linked Horizon'],
      ['Shinzou wo Sasageyo!', 'Linked Horizon'],
      ['The Day', 'Porno Graffitti'],
      ['Peace Sign', 'Kenshi Yonezu'],
      ['Gurenge', 'LiSA'],
      ['Homura', 'LiSA'],
      ['Crossing Field', 'LiSA'],
      ['Unravel', 'TK from Ling tosite sigure'],
      ['Silhouette', 'KANA-BOON'],
      ['Blue Bird', 'Ikimonogakari'],
      ['Again', 'YUI'],
      ['COLORS', 'FLOW'],
      ['Sign', 'FLOW'],
      ['Kaikai Kitan', 'Eve'],
      ['SPECIALZ', 'King Gnu'],
      ['Ready Steady Go', "L'Arc~en~Ciel"],
      ['We Are!', 'Hiroshi Kitadani'],
      ['Mixed Nuts', 'Official HIGE DANdism'],
      ['Sha la la', 'Garnet Crow'],
      ['Butter-Fly', 'Kouji Wada'],
      ['Moonlight Densetsu', 'DALI'],
      ['Odd Future', 'Hiroyuki Sawano'],
      ['Sorairo Days', 'Shoko Nakagawa'],
    ],
  },
  {
    id: 'vgm', name: 'Video Game Music', emoji: '🎮', looseArtist: true,
    blurb: 'Chiptunes to full orchestras',
    tracks: [
      ['MEGALOVANIA', 'Toby Fox'],
      ['Hopes and Dreams', 'Toby Fox'],
      ['Bonetrousle', 'Toby Fox'],
      ['Sweden', 'C418'],
      ['Wet Hands', 'C418'],
      ['Mice On Venus', 'C418'],
      ['Still Alive', 'Jonathan Coulton'],
      ['Want You Gone', 'Jonathan Coulton'],
      ['One-Winged Angel', 'Nobuo Uematsu'],
      ["Aerith's Theme", 'Nobuo Uematsu'],
      ["Terra's Theme", 'Nobuo Uematsu'],
      ['Last Surprise', 'Lyn'],
      ['Life Will Change', 'Lyn'],
      ['Rivers in the Desert', 'Lyn'],
      ['Weight of the World', 'Keiichi Okabe'],
      ['A Beautiful Song', 'Keiichi Okabe'],
      ['BFG Division', 'Mick Gordon'],
      ['Rip & Tear', 'Mick Gordon'],
      ['Halo Theme', "Martin O'Donnell"],
      ['Dragonborn', 'Jeremy Soule'],
      ['Reach for the Summit', 'Lena Raine'],
      ['Resurrections', 'Lena Raine'],
      ['Hornet', 'Christopher Larkin'],
      ['Floral Fury', 'Kristofer Maddigan'],
      ['Escape From the City', 'Crush 40'],
      ['Live & Learn', 'Crush 40'],
      ['Baba Yetu', 'Christopher Tin'],
      ['Lonely Rolling Star', 'Yuu Miyake'],
      ['Stardew Valley Overture', 'ConcernedApe'],
      ['Ezios Family', 'Jesper Kyd'],
    ],
  },
  {
    id: 'latin', name: 'Latin & Reggaetón', emoji: '💃',
    blurb: 'Salsa, cumbia, perreo',
    tracks: [
      ['La Bamba', 'Ritchie Valens'],
      ['Oye Como Va', 'Santana'],
      ['Bamboleo', 'Gipsy Kings'],
      ['La Vida Es un Carnaval', 'Celia Cruz'],
      ['Vivir Mi Vida', 'Marc Anthony'],
      ['Suavemente', 'Elvis Crespo'],
      ['Bailando', 'Enrique Iglesias'],
      ['La Tortura', 'Shakira'],
      ["Hips Don't Lie", 'Shakira'],
      ['Gasolina', 'Daddy Yankee'],
      ['Danza Kuduro', 'Don Omar'],
      ['Despacito', 'Luis Fonsi'],
      ['Mi Gente', 'J Balvin'],
      ['Tusa', 'KAROL G'],
      ['PROVENZA', 'KAROL G'],
      ['Callaita', 'Bad Bunny'],
      ['Me Porto Bonito', 'Bad Bunny'],
      ['DAKITI', 'Bad Bunny'],
      ['Ella Baila Sola', 'Eslabon Armado'],
      ['La Bachata', 'Manuel Turizo'],
      ['Obsesion', 'Aventura'],
      ['Propuesta Indecente', 'Romeo Santos'],
      ['El Rey', 'Vicente Fernández'],
      ['Cielito Lindo', 'Pedro Infante'],
      ['Como La Flor', 'Selena'],
      ['Bidi Bidi Bom Bom', 'Selena'],
      ['Todo de Ti', 'Rauw Alejandro'],
      ['Lambada', 'Kaoma'],
      ['Livin la Vida Loca', 'Ricky Martin'],
      ['Macarena', 'Los Del Rio'],
    ],
  },
  {
    id: 'afro', name: 'Afrobeats & Amapiano', emoji: '🌍',
    blurb: 'Lagos, Accra and Johannesburg',
    tracks: [
      ['Water No Get Enemy', 'Fela Kuti'],
      ['Zombie', 'Fela Kuti'],
      ['Pata Pata', 'Miriam Makeba'],
      ['Yeke Yeke', 'Mory Kanté'],
      ['Oliver Twist', "D'banj"],
      ['Personally', 'P-Square'],
      ['Ojuelegba', 'WizKid'],
      ['Come Closer', 'WizKid'],
      ['Essence', 'WizKid'],
      ['Fall', 'Davido'],
      ['If', 'Davido'],
      ['Unavailable', 'Davido'],
      ['Ye', 'Burna Boy'],
      ['On the Low', 'Burna Boy'],
      ['Last Last', 'Burna Boy'],
      ['City Boys', 'Burna Boy'],
      ['Peru', 'Fireboy DML'],
      ['Calm Down', 'Rema'],
      ['Soweto', 'Victony'],
      ['Terminator', 'Asake'],
      ['Joha', 'Asake'],
      ['Rush', 'Ayra Starr'],
      ['Kwaku the Traveller', 'Black Sherif'],
      ['SAD GIRLZ LUV MONEY', 'Amaarae'],
      ['Jerusalema', 'Master KG'],
      ['Mnike', 'Tyler ICU'],
      ['Adiwele', 'Young Stunna'],
      ['Osama', 'Zakes Bantwini'],
      ['Water', 'Tyla'],
      ['love nwantiti', 'CKay'],
    ],
  },
  {
    id: 'reggae', name: 'Reggae & Dancehall', emoji: '🇯🇲',
    blurb: 'Ska, roots, dub, bashment',
    tracks: [
      ['No Woman, No Cry', 'Bob Marley & The Wailers'],
      ['Three Little Birds', 'Bob Marley & The Wailers'],
      ['Jamming', 'Bob Marley & The Wailers'],
      ['Could You Be Loved', 'Bob Marley & The Wailers'],
      ['Buffalo Soldier', 'Bob Marley & The Wailers'],
      ['The Harder They Come', 'Jimmy Cliff'],
      ['Many Rivers to Cross', 'Jimmy Cliff'],
      ['Pressure Drop', 'Toots & The Maytals'],
      ["54-46 That's My Number", 'Toots & The Maytals'],
      ['Israelites', 'Desmond Dekker'],
      ['Legalize It', 'Peter Tosh'],
      ['Night Nurse', 'Gregory Isaacs'],
      ['Police & Thieves', 'Junior Murvin'],
      ['Bam Bam', 'Sister Nancy'],
      ['Murder She Wrote', 'Chaka Demus & Pliers'],
      ['Here Comes the Hotstepper', 'Ini Kamoze'],
      ['Boombastic', 'Shaggy'],
      ["It Wasn't Me", 'Shaggy'],
      ['Get Busy', 'Sean Paul'],
      ['Temperature', 'Sean Paul'],
      ['Gimme the Light', 'Sean Paul'],
      ['Welcome to Jamrock', 'Damian Marley'],
      ['Hold Yuh', 'Gyptian'],
      ['Toast', 'Koffee'],
      ['Rapture', 'Koffee'],
      ['Under Mi Sensi', 'Barrington Levy'],
      ['Rude Boy', 'Rihanna'],
      ['A Message to You Rudy', 'The Specials'],
    ],
  },
  {
    id: 'desi', name: 'Bollywood & Desi', emoji: '🪷',
    blurb: 'Filmi, bhangra and Punjabi pop',
    tracks: [
      ['Chaiyya Chaiyya', 'Sukhwinder Singh'],
      ['Jai Ho', 'A. R. Rahman'],
      ['Kun Faya Kun', 'A. R. Rahman'],
      ['Tum Hi Ho', 'Arijit Singh'],
      ['Channa Mereya', 'Arijit Singh'],
      ['Kesariya', 'Arijit Singh'],
      ['Ae Dil Hai Mushkil', 'Arijit Singh'],
      ['Gerua', 'Arijit Singh'],
      ['Naatu Naatu', 'Rahul Sipligunj'],
      ['Srivalli', 'Sid Sriram'],
      ['Kal Ho Naa Ho', 'Sonu Nigam'],
      ['Tujhe Dekha To', 'Kumar Sanu'],
      ['Dola Re Dola', 'Shreya Ghoshal'],
      ['Deewani Mastani', 'Shreya Ghoshal'],
      ['Sheila Ki Jawani', 'Sunidhi Chauhan'],
      ['Munni Badnaam Hui', 'Mamta Sharma'],
      ['Malhari', 'Vishal Dadlani'],
      ['Balam Pichkari', 'Vishal Dadlani'],
      ['Lungi Dance', 'Yo Yo Honey Singh'],
      ['Brown Rang', 'Yo Yo Honey Singh'],
      ['Mundian To Bach Ke', 'Panjabi MC'],
      ['Laung Laachi', 'Mannat Noor'],
      ['Lahore', 'Guru Randhawa'],
      ['Excuses', 'AP Dhillon'],
      ['Brown Munde', 'AP Dhillon'],
      ['295', 'Sidhu Moose Wala'],
      ['Pasoori', 'Ali Sethi'],
      ['Afreen Afreen', 'Nusrat Fateh Ali Khan'],
    ],
  },
  {
    id: 'funk', name: 'Disco, Funk & Boogie', emoji: '🕺',
    blurb: 'Basslines that will not quit',
    tracks: [
      ['Get Up (I Feel Like Being A) Sex Machine', 'James Brown'],
      ['I Got You (I Feel Good)', 'James Brown'],
      ['Give Up the Funk (Tear the Roof Off the Sucker)', 'Parliament'],
      ['Flash Light', 'Parliament'],
      ['One Nation Under a Groove', 'Funkadelic'],
      ['Le Freak', 'CHIC'],
      ['Good Times', 'CHIC'],
      ["Stayin' Alive", 'Bee Gees'],
      ['Night Fever', 'Bee Gees'],
      ['I Will Survive', 'Gloria Gaynor'],
      ['Dancing Queen', 'ABBA'],
      ['September', 'Earth, Wind & Fire'],
      ['Boogie Wonderland', 'Earth, Wind & Fire'],
      ['Got to Be Real', 'Cheryl Lynn'],
      ['I Feel Love', 'Donna Summer'],
      ['Hot Stuff', 'Donna Summer'],
      ['Play That Funky Music', 'Wild Cherry'],
      ['Brick House', 'Commodores'],
      ['Super Freak', 'Rick James'],
      ["Rapper's Delight", 'The Sugarhill Gang'],
      ['Ladies Night', 'Kool & The Gang'],
      ['Celebration', 'Kool & The Gang'],
      ['Word Up!', 'Cameo'],
      ['Thank You (Falettinme Be Mice Elf Agin)', 'Sly & The Family Stone'],
      ['Pick Up the Pieces', 'Average White Band'],
      ['Car Wash', 'Rose Royce'],
      ['Y.M.C.A.', 'Village People'],
      ["Ain't Nobody", 'Chaka Khan'],
    ],
  },
  {
    id: 'indie', name: 'Indie & Bedroom Pop', emoji: '🌙',
    blurb: 'Reverb, Bandcamp and slow-burn hits',
    tracks: [
      ['Float On', 'Modest Mouse'],
      ['Such Great Heights', 'The Postal Service'],
      ['Skinny Love', 'Bon Iver'],
      ['Holocene', 'Bon Iver'],
      ['Two Weeks', 'Grizzly Bear'],
      ['Young Folks', 'Peter Bjorn and John'],
      ['Home', 'Edward Sharpe & The Magnetic Zeros'],
      ['Little Talks', 'Of Monsters and Men'],
      ['Pumped Up Kicks', 'Foster the People'],
      ['Electric Feel', 'MGMT'],
      ['Kids', 'MGMT'],
      ['Time to Pretend', 'MGMT'],
      ['Lisztomania', 'Phoenix'],
      ['1901', 'Phoenix'],
      ['Sweater Weather', 'The Neighbourhood'],
      ['Riptide', 'Vance Joy'],
      ['Video Games', 'Lana Del Rey'],
      ['Motion Sickness', 'Phoebe Bridgers'],
      ['The Night We Met', 'Lord Huron'],
      ['Heat Waves', 'Glass Animals'],
      ['Sofia', 'Clairo'],
      ['Pretty Girl', 'Clairo'],
      ['Are You Bored Yet?', 'Wallows'],
      ['Space Song', 'Beach House'],
      ['Telepatía', 'Kali Uchis'],
      ['Line Without a Hook', 'Ricky Montgomery'],
      ['She', 'Tyler, The Creator'],
      ['White Winter Hymnal', 'Fleet Foxes'],
    ],
  },
  {
    id: 'screen', name: 'Movie & TV Themes', emoji: '🎬', looseArtist: true,
    blurb: 'Scores and title sequences',
    tracks: [
      ['The Imperial March', 'John Williams'],
      ['Main Title', 'John Williams'],
      ['Raiders March', 'John Williams'],
      ['Jurassic Park Theme', 'John Williams'],
      ["Hedwig's Theme", 'John Williams'],
      ['Time', 'Hans Zimmer'],
      ['Cornfield Chase', 'Hans Zimmer'],
      ["He's a Pirate", 'Klaus Badelt'],
      ['Now We Are Free', 'Hans Zimmer'],
      ['The Godfather Waltz', 'Nino Rota'],
      ['The Good, the Bad and the Ugly', 'Ennio Morricone'],
      ['Gonna Fly Now', 'Bill Conti'],
      ['Axel F', 'Harold Faltermeyer'],
      ['Ghostbusters', 'Ray Parker Jr.'],
      ['Eye of the Tiger', 'Survivor'],
      ['My Heart Will Go On', 'Celine Dion'],
      ['Circle of Life', 'Carmen Twillie'],
      ['Let It Go', 'Idina Menzel'],
      ['A Whole New World', 'Peabo Bryson'],
      ["Mia & Sebastian's Theme", 'Justin Hurwitz'],
      ['Merry Christmas Mr. Lawrence', 'Ryuichi Sakamoto'],
      ["Comptine d'un autre été", 'Yann Tiersen'],
      ["One Summer's Day", 'Joe Hisaishi'],
      ['Merry-Go-Round of Life', 'Joe Hisaishi'],
      ['The X-Files', 'Mark Snow'],
      ['Woke Up This Morning', 'Alabama 3'],
      ['Main Title Theme', 'Ramin Djawadi'],
      ['Red Right Hand', 'Nick Cave & The Bad Seeds'],
    ],
  },
  {
    id: 'online', name: 'Phonk & Internet', emoji: '💾',
    blurb: 'Songs that escaped from a feed',
    tracks: [
      ['Never Gonna Give You Up', 'Rick Astley'],
      ['All Star', 'Smash Mouth'],
      ['Through the Fire and Flames', 'DragonForce'],
      ['Crab Rave', 'Noisestorm'],
      ['Astronomia', 'Vicetone'],
      ['bad guy', 'Billie Eilish'],
      ["Gangsta's Paradise", 'Coolio'],
      ['Murder in My Mind', 'Kordhell'],
      ['Metamorphosis', 'INTERWORLD'],
      ['Close Eyes', 'DVRST'],
      ['Sahara', 'Hensonn'],
      ['Doja', 'Central Cee'],
      ['money machine', '100 gecs'],
      ['hand crushed by a mallet', '100 gecs'],
      ['Kyoto', 'Skrillex'],
      ['Cbat', 'Hudson Mohawke'],
      ['Running Up That Hill', 'Kate Bush'],
      ['Bury the Light', 'Casey Edwards'],
      ['Rasputin', 'Boney M.'],
      ['Dernière Danse', 'Indila'],
      ['Bloody Mary', 'Lady Gaga'],
      ['Murder On the Dancefloor', 'Sophie Ellis-Bextor'],
      ['Sleepwalking', 'Bring Me the Horizon'],
      ['MONEY', 'LISA'],
      ['Renai Circulation', 'Kana Hanazawa'],
      ['Dr. Wily Stage 1', 'Bulby'],
      ['Africa', 'TOTO'],
      ['Take Me to Church', 'Hozier'],
    ],
  },
  {
    id: 'brasil', name: 'Brasil', emoji: '🇧🇷',
    blurb: 'Bossa, MPB, tropicália, funk carioca',
    tracks: [
      ['Garota de Ipanema', 'João Gilberto'],
      ['Desafinado', 'João Gilberto'],
      ['Águas de Março', 'Elis Regina'],
      ['Como Nossos Pais', 'Elis Regina'],
      ['Chega de Saudade', 'Antônio Carlos Jobim'],
      ['Wave', 'Antônio Carlos Jobim'],
      ['Construção', 'Chico Buarque'],
      ['Alegria, Alegria', 'Caetano Veloso'],
      ['Sozinho', 'Caetano Veloso'],
      ['Tropicália', 'Caetano Veloso'],
      ['Aquele Abraço', 'Gilberto Gil'],
      ['Palco', 'Gilberto Gil'],
      ['Ponta de Lança Africano', 'Jorge Ben Jor'],
      ['Mas Que Nada', 'Jorge Ben Jor'],
      ['Pais e Filhos', 'Legião Urbana'],
      ['Tempo Perdido', 'Legião Urbana'],
      ['Ainda Bem', 'Marisa Monte'],
      ['Beija Eu', 'Marisa Monte'],
      ['Ai Se Eu Te Pego', 'Michel Teló'],
      ['Balada', 'Gusttavo Lima'],
      ['Evidências', 'Chitãozinho & Xororó'],
      ['Deixa Acontecer', 'Grupo Revelação'],
      ['Trem-Bala', 'Ana Vilela'],
      ['Envolver', 'Anitta'],
      ['Vai Malandra', 'Anitta'],
      ['Baile de Favela', 'MC João'],
      ['Bum Bum Tam Tam', 'MC Fioti'],
      ['Girl from Rio', 'Anitta'],
    ],
  },
  {
    id: 'french', name: 'Chanson & French Touch', emoji: '🇫🇷',
    blurb: 'Accordions to filtered house',
    tracks: [
      ['La Vie en rose', 'Édith Piaf'],
      ['Non, je ne regrette rien', 'Édith Piaf'],
      ['Ne me quitte pas', 'Jacques Brel'],
      ['La Bohème', 'Charles Aznavour'],
      ["Comme d'habitude", 'Claude François'],
      ["Je t'aime... moi non plus", 'Serge Gainsbourg'],
      ['Bonnie and Clyde', 'Serge Gainsbourg'],
      ['Les Champs-Élysées', 'Joe Dassin'],
      ['Voyage Voyage', 'Desireless'],
      ['Joe le taxi', 'Vanessa Paradis'],
      ['Alors on danse', 'Stromae'],
      ['Papaoutai', 'Stromae'],
      ['Formidable', 'Stromae'],
      ['Tous les mêmes', 'Stromae'],
      ['Ta Reine', 'Angèle'],
      ['Balance ton quoi', 'Angèle'],
      ['Djadja', 'Aya Nakamura'],
      ['Flat Beat', 'Mr. Oizo'],
      ['Sexy Boy', 'Air'],
      ["La femme d'argent", 'Air'],
      ['Lady (Hear Me Tonight)', 'Modjo'],
      ['Genesis', 'Justice'],
      ['D.A.N.C.E.', 'Justice'],
      ['Je veux', 'ZAZ'],
      ['Dernière Danse', 'Indila'],
      ['Foule sentimentale', 'Alain Souchon'],
      ['Aline', 'Christophe'],
      ['Pour que tu maimes encore', 'Celine Dion'],
    ],
  },
];

// Flat list with stable ids — this is what the guess autocomplete searches.
export const ALL_TRACKS = PACKS.flatMap((pack) =>
  pack.tracks.map(([title, artist], i) => ({
    id: `${pack.id}:${i}`,
    packId: pack.id,
    packName: pack.name,
    title,
    artist,
    label: `${title} — ${artist}`,
  }))
);

export const PACK_BY_ID = Object.fromEntries(PACKS.map((p) => [p.id, p]));
